### ISSUE TITLE
Feature Request: Thumbnails for images

### ISSUE THREAD

**Issue by DrErfinder** [filegator/filegator#10]
Would it be possible to have thumbnails for image files?
Maybe in conjunction with a grid view for folders with images.

**Comment by mujtaba989** [comment]
possibe to add lightbox gallery??

**Comment by alcalbg** [comment]
Check the latest version https://demo.filegator.io

**Comment by DrErfinder** [comment]
Appreciate the work. But I'd still love to see grid view where i could all the images a folder contains at a glance. If you have sort a lot of images "opening" each image individually is exceedingly time consuming.

**Comment by alcalbg** [comment]
We are getting there... check again https://demo.filegator.io

**Comment by Openuser87** [comment]
Second the feature request. Looked at the demo but could not figure out how to show a thumbnail grid. If it's already implemented - could you give a hint?

**Comment by panlina** [comment]
As of now you can click "View" on a image file to open a thumbnail list in a modal. However I feel a thumbnail view is still desired.

**Comment by status201** [comment]
A grid view with thumbnails (and filetype icons for non-images?) would make a huge difference for my use case as well..
Pretty please... ;-)

**Comment by oh1apps** [comment]
up, up! thubnails would be handy

**Comment by nomaxtech** [comment]
Bump for a grid view option with image previews/thumbnails.
