### ISSUE TITLE
Auto login using POST 

### ISSUE THREAD

**Issue by ned-code** [filegator/filegator#100]
I'd like to create a few auto login scripts that use POST method to enter username and password, as described here https://afterlogic.com/docs/webmail-lite/integration-and-development/sending-login-credentials-via-post 

But File Gator doesn't use a static login page (with fixed url).  Any suggestions?

**Comment by mckaygerhard** [comment]
It seems a good way to integrate with some intranet's! @alcalbg

**Comment by alcalbg** [comment]
Try with this:

Method: `POST`
Route: `/?r=/login`
Payload: `{"username":"jane","password":"jane"}`

You might also need to disable csrf_protection in your configuration.php file (set to false).
