### ISSUE TITLE
Suggestion: Add move files permission separate from edit permission

### ISSUE THREAD

**Issue by Gerdofal** [filegator/filegator#106]
Edit: Just saw that my admin can move files around, but my users can't. Maybe what's really needed is a move files permission separate from the edit permission?

_

> Would love to see an option to move files around, either to a subfolder, or out of a subfolder to the root folder. Right-click or ... menu would be fine, though drag and drop handles would be a nice bonus.

_

**Comment by alcalbg** [comment]
Hi,

Thanks for your suggestion, however, there are no 'edit' permissions, see here https://docs.filegator.io/accounts.html

Moving (or renaming) is effectively a 'write' operation, this is how it works in most filesystems.
