### ISSUE TITLE
Cannot view/edit .json files

### ISSUE THREAD

**Issue by Lupul** [filegator/filegator#110]
I have enabled '.json' file editing in `$dist_config['frontend_config']['editable']` but the editor modal doesn't display the file content.
- The http GET request is succesfull. I can see the encoded file content in the http response payload
- I get this error in the Browser console every time i click on a .json file: TypeError: "this.codeData.split is not a function"
![image](https://user-images.githubusercontent.com/3596864/85229052-34591e00-b3f0-11ea-9cd9-e9a0486462eb.png)

Env:
 - FileGator Version 7.4.1
 - Server: Ubuntu 18.04
 - PHP 7.4
 - Browser: Firefox or Chome

**Comment by alcalbg** [comment]
This should be fixed with the latest commit, can you please confirm?

Thanks!

**Comment by Lupul** [comment]
Yes, it is working fine now, thanks.

PS: Congrats for creating this project, I really enjoy using it and also noticed it is very cleanly coded :+1: Good Job!

**Comment by alcalbg** [comment]
Awesome, don't forget to star this repo ;)

Cheers!
