### ISSUE TITLE
Feature Chmod / Chown folders / files

### ISSUE THREAD

**Issue by jaapmarcus** [filegator/filegator#112]
We currently build in Filegator inside our "Hosting Control Panel" [HestiaCP](https://hestiacp.com)/[Github](https://github.com/hestiacp/hestiacp) and we love it... 

How ever I would like if there could add a option added to chmod / chown a folder or file. As sometimes is required for websites?

**Comment by alcalbg** [comment]
Hi,

Unfortunately, this is not supported by the underlying flysystem, see https://github.com/thephpleague/flysystem/issues/137

However, you can set default visibility (private/public) as described here: https://flysystem.thephpleague.com/v1/docs/usage/setup/#global-configuration

**Comment by jaapmarcus** [comment]
Thank you any way.

**Comment by divinity76** [comment]
seems chmod support has been implemented in flysystem at some point? ref https://flysystem.thephpleague.com/docs/usage/unix-visibility/
