### ISSUE TITLE
Open PDF in tab instead of download?

### ISSUE THREAD

**Issue by Gerdofal** [filegator/filegator#115]
When a PDF file is clicked, it is downloaded by the browser (Chrome) instead of opening in a new tab. Is this something that can be changed in settings or is it inherent to having the files pushed out by Filegator?

**Comment by alcalbg** [comment]
Hi,

You must have been using the older version, this feature was added in #51

Please [upgrade](https://docs.filegator.io/install.html#upgrade).

**Comment by Gerdofal** [comment]
Yes, that worked. Thanks!
