### ISSUE TITLE
Security report

### ISSUE THREAD

**Issue by Blackend** [filegator/filegator#116]
**Describe the bug**
The guest can view the contents of any higher-level directory.

**To Reproduce**
1. Open site with guest view.
2. Press "Home" button.
3. Edit address bar and change "?cd=%2F" to "?cd=.."

**Expected behavior**
Show only content set by the administrator.

**Screenshots**

**Normal behavior:**
![image](https://user-images.githubusercontent.com/53617677/88651929-77cb3a00-d0ca-11ea-966e-f47e36db0a08.png)

**Modified path:**
![image](https://user-images.githubusercontent.com/53617677/88652031-94677200-d0ca-11ea-8018-4ee04f25f009.png)

**Environment (please complete the following information):**
 - FileGator Version [e.g. 7.4.3]
 - Server: [nginx/1.14.2]
 - PHP Version [PHP 7.3.14]

**Comment by alcalbg** [comment]
Thanks for reporting this, it should be fixed now.

Please check the [security guidelines](https://github.com/filegator/filegator#security) as well.

**Comment by Blackend** [comment]
Yes, fixed :) Thank You.
