### ISSUE TITLE
Upload problem when filename contains national characters

### ISSUE THREAD

**Issue by Vaidas777** [filegator/filegator#12]
If uploaded filename is "ąčęėįšųū.txt" the uploaded filename on the server becomes ".txt".

If uploaded  filename is "456-ąčęėįšųū.txt" uploaded filename on the server is "456-ąčęėįšųū.txt", but all folder and files disappear from the filegator listing.

Filegator 7.0.1, Ubuntu 18.04 with apache2.4 and php 7.2

**Comment by alcalbg** [comment]
Thanks for reporting this. Can you try with new version 7.1.0 please?

**Comment by Vaidas777** [comment]
Sorry for delay with answer. The second problem was solved in 7.1.1, but the first one (If uploaded filename is "ąčęėįšųū.txt" the uploaded filename on the server becomes ".txt".) - no.

**Comment by alcalbg** [comment]
You're right, it fails again.

I've added another fix and few tests to cover this bug. Could you try one more time with 7.1.2 please?

**Comment by Vaidas777** [comment]
Thanks. The problem solved.
