### ISSUE TITLE
Improvement: Add personal php code to file manager index

### ISSUE THREAD

**Issue by josuhap** [filegator/filegator#122]
Hi guys, this is my first time posting on github, I hope doing well 😋 .

I would like to add personal php code to the main page (file manager).
I have been read and doing some tests but it does not work:

I have tested(adding include php lines) on:

dist\js\app.js
dist\main.html
backend\Services\View\Adapters\Vuejs.php

Any idea?

Thank you in advance!

**Comment by alcalbg** [comment]
Hi,

If you're thinking about adding code to the front-end (the visual part) then this must me done in javascript/vuejs not php. You can also try with 'add_to_body' configuration parameter, see https://docs.filegator.io/configuration/basic.html#additional-html

**Comment by josuhap** [comment]
Hi @alcalbg, Thanks for your response.

I have tried already with this code

`incluye ('tst.php');`

tst.php
`<? echo 'test for filegator';? >`

It appears on the top of the website but quickly dissapear. My idea is include personal code from another php file and just add one or two lines to the "oficial code".

Thanks!

**Comment by alcalbg** [comment]
I guess you could do something like this:

in configuration.php
```
'add_to_body' => include('test.php'),
```
then in test.php
```
<?php return 'test for filegator';
```
Note the return statement here, you are returning the string.

The string should appear at the bottom, however, this is a bad practice imho.

**Comment by josuhap** [comment]
Thanks for your help,

I had to delete from app.css 

`#wrapper{heigh: 100%}`


Thanks again!
