### ISSUE TITLE
Files downloaded from website fail to upload without showing error

### ISSUE THREAD

**Issue by Gerdofal** [filegator/filegator#127]
**Describe the bug**
A file, such as a PDF, downloaded from a website when then uploaded via FileGator fails to upload and shows no error in any log or in the browser console. This appears to be security related in some way, the files are downloaded with the flag that they were downloaded from the web and "may present a security risk".

A workaround for this is to open it in Adobe Reader and then re-save it as a new name and upload that version.

The main bug here is that there is no error message when this happens.

Using Google Chrome

**To Reproduce**
1. Drag file in... everything seems to work as expected

**Expected behavior**
An error window should show up if a file is not working for some reason.

**Logs**
No errors present in php, app, or console.

**Environment (please complete the following information):**
 - FileGator Version [e.g. 7.0.0]
 - Server: IIS
 - PHP Version- 7.2.7
 - Browser - Chrome

**Additional context**

**Comment by alcalbg** [comment]
Hi,

Thanks for reporting this.

Are you using (or have you tried with) the latest filegator version 7.4.4?

**Comment by Gerdofal** [comment]
7.4.3 actually. Let me see about getting an update done on that.

**Comment by alcalbg** [comment]
Unfortunately, I am not able to reproduce this yet.

Is anyone else getting this bug?

**Comment by cvmanjoo** [comment]
Hi,

Even I tired, pdf uploads fine. Couldn't reproduce this.

Thanks
