### ISSUE TITLE
How to turn on resume from break-point  and multithreading？

### ISSUE THREAD

**Issue by dianjiweiling** [filegator/filegator#13]

**Comment by alcalbg** [comment]
Can you please elaborate a bit more?

**Comment by dianjiweiling** [comment]
I download file use adm pro from server,and it toast 
> ADM Pro: ADM: server does not
support resuming and multi-threading
download&pathL21pdWIFTEFWRU5ERVJfOS4
5LjNfNWNhMThlNjEyMF85LjAueml

so i wonder how to enable server resuming and multi-threading

**Comment by alcalbg** [comment]
Filegator does not support this feature yet (https://en.wikipedia.org/wiki/Byte_serving) so you cannot simply enable it. Further more, I don't think multi-threading is possible in PHP, at least not in web context.

**Comment by dianjiweiling** [comment]
i want to use multi-threading because of the download speed is only 2m/s in local area network, but the upload speed is 5m/s. Can the download speed be improved?

**Comment by darkmoh** [comment]
Hi please how config with resume downloading files by internet download manager ( resume capability )
