### ISSUE TITLE
Download is broken

### ISSUE THREAD

**Issue by avinashseth** [filegator/filegator#131]
**Describe the bug**
Team member uploads the file, copies the link but when we visit the link, download does not happen! It simply redirects us to homepage(login page if not logged in)

**To Reproduce**
Upload the file
Click on 3 dots, click copy link
Try visiting that copied link from private tab

**Expected behavior**
It should download the file

**Environment (please complete the following information):**
 - FileGator Version 7.4.4
 - Server: Apache 2.4
 - PHP Version 7.4
 - Browser All

**Additional context**
Sometimes it works, sometimes it doesn't!

**Comment by alcalbg** [comment]
Duplicate #117
