### ISSUE TITLE
How to access a custom php file

### ISSUE THREAD

**Issue by tarikko** [filegator/filegator#133]
How to access a php file i uploaded with an http request ?
example : 
hello_world.php:
`<?php echo "hello world"; ?>`
then i type the http request:
`www.mydomain.com/?path=<link to hello_world.php>`
then i want to see "hello world" displayed on my webpage wich means that the browser ran the php file successfully
pls help me

**Comment by alcalbg** [comment]
Hi,

First, upload your hello_world.php file to your server and make sure www.yourdomain.com/hello_word.php works as expected.

Next, find out what is the full path where this hello_world.php file is located (for example /var/www/html/test/hello_world.php)

Finally, install filegator and point your repository path to this exact folder as described in the [docs](https://docs.filegator.io/configuration/storage.html)
```
return new \League\Flysystem\Adapter\Local(
                      '/var/www/html/test/'
                      );
```

Now you should be able to manage all your 'live' files with filegator and see your webpage updated accordingly.

Hope this make sense
