### ISSUE TITLE
how to make the following configurations

### ISSUE THREAD

**Issue by kainpro** [filegator/filegator#137]
Hello good afternoon, How can I disable copy, move and copy options link?
![image](https://user-images.githubusercontent.com/65268233/93344491-5ef02280-f7f7-11ea-9c52-b528a61965ec.png)

And where I can Edit Label "add files"?

![image](https://user-images.githubusercontent.com/65268233/93345083-0a997280-f7f8-11ea-8097-797bcc525ae0.png)

Possibility of opening the images in a new tab and not in a frame

![image](https://user-images.githubusercontent.com/65268233/93347330-901e2200-f7fa-11ea-89f7-ec353e9968c9.png)

**Comment by kainpro** [comment]
Found it

**Comment by K-J-VV** [comment]
> Possibility of opening the images in a new tab and not in a frame

@kainpro any advice on how to open image in a new tab? Would be much appreciated
