### ISSUE TITLE
Use existing Login not filegator login

### ISSUE THREAD

**Issue by bogs03** [filegator/filegator#139]
Hi, 
I have a question, I have existing login of our system, I want to use it instead of login on the filegator. How can I redirect on the file directory after I log in on my existing login on our system?
![Existing login on system](https://user-images.githubusercontent.com/20350920/94505740-59a2c700-023e-11eb-8540-6cfb0e48bece.JPG)
![file directory after login on filegator](https://user-images.githubusercontent.com/20350920/94505743-5b6c8a80-023e-11eb-9bfa-5ee2e9ff1ce7.JPG)

**Comment by alcalbg** [comment]
Hi,

You can achieve this by creating your own custom Auth adapter.

See https://docs.filegator.io/configuration/auth.html
