### ISSUE TITLE
Don't force file download / hotlinking

### ISSUE THREAD

**Issue by bielej** [filegator/filegator#141]
When one uses the _Copy link_ or _Download_ button the file gets downloaded in the browser.
Is it be possible to disable the forced download and allow the browser to handle the file? 
This would allow opening multimedia files directly in the browser without downloading them as well as hotlinking of images.

**Comment by alcalbg** [comment]
This is controlled by Content-Disposition header (inline option). 

We have this enabled for pdf file, see here: https://github.com/filegator/filegator/blob/master/backend/Controllers/DownloadController.php#L75

**Comment by bielej** [comment]
So commenting out the `if` statement as follows
```
74 //        if ($contentType == 'application/pdf') {
75             $disposition = HeaderUtils::DISPOSITION_INLINE;
76 //        }
```
indeed works - the files are not downloaded automatically.
Could you make this configurable in the `configuration.php` file?

**Comment by alcalbg** [comment]
This will be included in the next release.

Thanks!

**Comment by alcalbg** [comment]
Done. Can you try this?

**Comment by bielej** [comment]
Works as intended, thank you :)
