### ISSUE TITLE
HTTP 405 on OPTIONS request even if Cors service is enabled

### ISSUE THREAD

**Issue by zbx1425** [filegator/filegator#142]
**Describe the bug**
I am attempting to seperate the frontend and backend on two different servers. I enabled the Cors service, and set up the correct cookie policy for the HttpFoundation.
GET requests and cookies worked fine. However, POST requests (login) all failed because "HTTP 405 Not Allowed" was returned for every CORS preflight request.

**To Reproduce**
1. Run filegator backend on one host with Cors on
```
'Filegator\Services\Session\SessionStorageInterface' => [
    'handler' => '\Filegator\Services\Session\Adapters\SessionStorage',
    'config' => [
        'handler' => function () {
            $save_path = null;
            $handler = new \Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler($save_path);
            return new \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage(["cookie_samesite" => "None", "cookie_secure" => true], $handler);
        },
    ],
],
'Filegator\Services\Cors\Cors' => [
    'handler' => '\Filegator\Services\Cors\Cors',
    'config' => [
        'enabled' => true,
    ],
],
```
2. Run filegator frontend on another host, and configure it to use the api of the first host, by setting the `VUE_APP_API_ENDPOINT` in .env.production
3. The frontend can fetch the config and display the login form, but cannot log in

**Expected behavior**
HTTP 200 or 204 is returned for preflight requests, so that Cors works as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/25097028/95676401-781aa200-0bf0-11eb-9d00-f9489e1e983e.png)

**Environment (please complete the following information):**
 - FileGator 7.1.6
 - Server: Nginx 1.18.0 on Arm64 OpenWRT
 - PHP 7.4.9
 - Chrome 85.0.4183.121

**Comment by alcalbg** [comment]
Hi,

Thank you for your detailed report.

Unfortunately, I cannot reproduce this using my two domains:

![rep](https://user-images.githubusercontent.com/1578476/95737365-d777c100-0c87-11eb-9a7b-a1f92fce413f.png)

Chrome Version 85.0.4183.121 (Official Build) (64-bit)

See if your chrome is complaining about something else, perhaps missing https for cookies or something like that. Also can you try this with incognito mode or with Firefox?

**Comment by zbx1425** [comment]
Thanks for handling my issue!

I pushed the latest frontend and backend onto my production server.
Unfortunately it still doesn't work, in both chrome and firefox.
I have little knowledge over CORS, so thanks for your help!

![image](https://user-images.githubusercontent.com/25097028/95742446-9d77e080-0cc2-11eb-8137-6620899a5ee0.png)
![image](https://user-images.githubusercontent.com/25097028/95742512-b7b1be80-0cc2-11eb-96c4-0ecfb640dd4e.png)

For troubleshooting you can access the production server at [https://storage.bvecs.tk/main.html](https://storage.bvecs.tk/main.html). A test account is available with the username "guest" and the password "admin123".
For comparison, another frontend is deployed at the same domain as backend (https://api.zbx1425.tk:8953/bcs-src/filegator), which worked fine.

**Comment by alcalbg** [comment]
For GET request you get all access-control headers in the response:
![get](https://user-images.githubusercontent.com/1578476/95743590-4b1ecb80-0c92-11eb-93de-50626ff98362.png)

But for OPTIONS you don't get any of that:
![options](https://user-images.githubusercontent.com/1578476/95743648-5eca3200-0c92-11eb-8e93-b8e1bc8b62e4.png)

I also cannot see powered-by php in OPTIONS response, so I suspect this request is cut before it reaches php, maybe nginx does not allow OPTIONS to pass through...

**Comment by alcalbg** [comment]
Yes, just checked with Postman, all OPTIONS methods are probably blocked by your nginx.

**Comment by zbx1425** [comment]
I see the problem. How stupid of me!
I thought nginx would proxy_pass OPTIONS requests, which is not the case.
Thanks a lot for your help.

**Comment by alcalbg** [comment]
Np, cheers!
