### ISSUE TITLE
Unknown Error: download or zip folders/files over 170MB

### ISSUE THREAD

**Issue by linusil** [filegator/filegator#144]
When I try to **download** or **zip** a folder or a file of **more than 170MB** filegator gives me an **unknown error** after around 30 seconds.
The app.log contains no information about this error. 
I am running **filegator 7.4.5.**

Does anyone have an idea what could cause the error?
**I am able to zip and download smaller files. 
Via FTP I can even zip huge files over 1GB.**

Thanks in advance,
Linus

**Comment by alcalbg** [comment]
Hi,

Your PHP probably needs more execution time to finish before it gets killed by the server. The default limit is 30 seconds.

You can try to increase the limit by adding these two lines on top of your `dist/index.php` file:
```
ini_set('max_execution_time', 300); //300 seconds = 5 minutes
ini_set('memory_limit','256M');
```
This might not work on some shared hosting plans. Their servers are configured to ignore these settings. They can also limit resource consumption in other ways preventing your scripts from taking up too many memory or processor cycles.

Docs:
https://www.php.net/manual/en/function.set-time-limit.php
https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time

**Comment by it-toppp** [comment]
How can you speed up the decompression process? Now the 50MB archive is unpacked for 20 minutes (servcer 1CPU 1RAM)
