### ISSUE TITLE
I have downloaded filegator precompiled build, it is working fine but not showing option for file view and edit.

### ISSUE THREAD

**Issue by sarikatekale** [filegator/filegator#150]
**Describe the bug**

**Comment by alcalbg** [comment]
Which file extension are you trying to edit?

Default in configuration.php is:
```
'editable' => ['.txt', '.css', '.js', '.ts', '.html', '.php', '.json', '.md'],
```

https://github.com/filegator/filegator/blob/master/configuration_sample.php#L19

**Comment by sarikatekale** [comment]
.txt, .xlsx

**Comment by sarikatekale** [comment]
Is there any way that,how can i can edit .xlsx file

**Comment by alcalbg** [comment]
No, only plain text files are supported at the moment

**Comment by sarikatekale** [comment]
Ok, Thank You
