### ISSUE TITLE
 Multiple clicks on sorting doesn't sort

### ISSUE THREAD

**Issue by Gui13** [filegator/filegator#152]
**Describe the bug**
Multiple clicks on sorting doesn't sort

**To Reproduce**
1. Click on sort by date => it works
2. Reclick on same sort, the arrow switches direction but the sorting doesn't happen

**Expected behavior**

Multiple clicks on the same sorting should invert the sorting

**Screenshots**

(this is a zipped video, I can't upload movs)

[Enregistrement de l’écran 2020-10-31 à 14.04.38.zip](https://github.com/filegator/filegator/files/5469108/Enregistrement.de.l.ecran.2020-10-31.a.14.04.38.zip)

**Logs**

No logs

**Environment (please complete the following information):**
 - FileGator Version 7.4.5
 - Server: Latest Apache (docker image "php:apache")
 - PHP Version - Last PHP version 
 - Browser  Firefox

**Additional context**

**Comment by alcalbg** [comment]
Hi,

Sorting algorithm has been changed in #148 and this should be fixed now. 

Can you please try with the latest filegator 7.4.6

Thanks!

**Comment by Gui13** [comment]
Indeed, thank you!
