### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by QiQiWan** [filegator/filegator#156]
**Describe the bug**
I have installed it on a server with Centos7 operatal system,  When I have configured httpd and php-fpm, the website can be opened normally, but after entering the account: admin/admin123, I can't log in by clicking the login button, prompting "unknow error" as shown in the following figure.
![](https://s1.ax1x.com/2020/11/04/Bg33ge.png)
![](https://s1.ax1x.com/2020/11/04/Bg3YDA.png)

The configuration file for the httpd service is as follows:

[httpd.conf](https://qiqi-1252510405.cos.ap-beijing.myqcloud.com/web/httpd.conf)

The user file is as follows:

[users.json](https://qiqi-1252510405.cos.ap-beijing.myqcloud.com/web/users.json)

**Comment by alcalbg** [comment]
There is not enough data to debug what is going on here. Please check your logs for errors:
```private/logs/app.log```
