### ISSUE TITLE
Blank lines in text editor

### ISSUE THREAD

**Issue by cdgco** [filegator/filegator#157]
**Describe the bug**
Every time I open a file on the text editor, it is prepended with 2 blank lines.

I have verified that this is happening on two different versions, on both the SFTP and FTP adapters, with a clean install aside from edited configuration, session adapter and authentication adapter files.

I'm wondering if this has something to do with a binary vs ascii transfer or translation of line endings?

Regardless, has this issue been seen before and is there any way to fix this, even if it's just a temporary fix that strips the textarea of preceeding lines?

**Environment (please complete the following information):**
 - FileGator Version 7.4.1 and 7.4.6
 - Server: nginx 1.19.3 + apache2 2.4.46 on Ubuntu 20.04
 - PHP-FPM Version 7.2
 - Browser: Google Chrome

**Comment by alcalbg** [comment]
Hi,

I was not able to reproduce this using sftp adapter and a simple test.txt file. Can you try with default local file system? I suspect this has something to do with ftp/sftp configuration.

![Screenshot 2020-11-17 at 10 09 34](https://user-images.githubusercontent.com/1578476/99369950-5b434f80-28bd-11eb-8242-eea20e23e2dc.png)
![Screenshot 2020-11-17 at 10 09 23](https://user-images.githubusercontent.com/1578476/99369958-5d0d1300-28bd-11eb-9b16-18f44b628b23.png)

**Comment by cdgco** [comment]
I still saw the behavior on the local filesystem, however, I decided to rewrite the configuration as my configuration file was somewhat complex. After reformatting it, the problem has gone away. Although I'm not sure which part of the configuration was causing this, it is fixed now. Thanks
