### ISSUE TITLE
Can't Upload

### ISSUE THREAD

**Issue by squarewav** [filegator/filegator#159]
Using centos 7 and php 7.4.

Can't seem to upload. The progress meter is just instantly 100%. Chrome inspector shows data being posted. Progress meter turns red but then nothing. Nothing occurs on the client, the file is not displayed, there is nothing in respository dir and nothing is logged. I can see chunks being posted in the httpd access log. But otherwise nothing happens.

Am I missing something?

**Comment by alcalbg** [comment]
Hi

- Check server logs (/var/log/apache2/error.log)
- Make sure your webserver can read and write to filegator/repository/ and all filegator/private/* folders

**Comment by squarewav** [comment]
In php.ini had to turn on:

  file_uploads = On

Strangely most results searching about this don't mention it. Maybe it's on by default and I turned it off as a precaution. Anyway I got uploads working now (although I ended up modifying simple-file-manger because I needed something super simple).

**Comment by alcalbg** [comment]
cool, closing this...
