### ISSUE TITLE
File upload gets stuck on empty file.

### ISSUE THREAD

**Issue by Travilo** [filegator/filegator#163]
**Describe the bug**
Uploading an empty file causes the progress bar to cycle forever. "Uploading 0% of 0 Bytes"

**To Reproduce**
Upload an empty file. Like test.txt with no contents.

**Expected behavior**
The empty file should upload.

**Environment (please complete the following information):**
 - FileGator online demo

**Comment by alcalbg** [comment]
Thanks for reporting this bug
