### ISSUE TITLE
Sorting of files is broken in Firefox

### ISSUE THREAD

**Issue by netesa** [filegator/filegator#17]
Changing of default sorting parameters (eg. sorting files by size, or by modification time) or changing of sorting order (ascending <-> descending) doesn't work in Firefox browser.

**Comment by alcalbg** [comment]
Thanks for reporting, it's already listed as broken here: https://github.com/filegator/filegator/blob/master/frontend/views/Browser.vue#L500

Any js guru available to look into this?
