### ISSUE TITLE
how to rename a file without opening the directory tree

### ISSUE THREAD

**Issue by kainpro** [filegator/filegator#185]
Hello, is there any way to rename a file without opening the tree with all the root directories?			

	renameItem: function(e) {
					return new Promise((function(a, n) {
						d.a.post("renameitem", {
							from: e.from,
							to: e.to,
							destination: e.destination
						}).then((function(e) {
							return a(e.data.data)
						}))["catch"]((function(e) {
							return n(e)
						}))
					}))
				},

**Comment by alcalbg** [comment]
Hi,

I don't think so. All operations are relative to the current working directory.

What would be the benefit of doing this kind of rename?

**Comment by kainpro** [comment]
I want something like the filegator demo.

![Captura de Pantalla 2021-02-18 a la(s) 7 59 34 a  m](https://user-images.githubusercontent.com/65268233/108360639-73c64d00-71bf-11eb-945e-13b0c90e5d16.png)

where it only opens a small modal to change the name.

additional I have been trying to rename a file in the demo and nothing happens?

**Comment by alcalbg** [comment]
You can't change files on the demo, it's read-only. 

Every feature you see there is included in the script, including this modal for renaming files.

**Comment by kainpro** [comment]
when I try to change the name of a file this modal opens

![Captura de Pantalla 2021-02-22 a la(s) 8 16 46 a  m](https://user-images.githubusercontent.com/65268233/108713602-75a54e80-74e6-11eb-9a60-440155b5a713.png)


In which file can I change it so that it appears similar to the demo?

**Comment by morph3us-net** [comment]
I did not have to change anything and when rightclicking -> renaming a file this modal pops up:
![filegator_rename](https://user-images.githubusercontent.com/43741267/108716506-81136c80-751c-11eb-80ea-38320ab04cd7.jpg)

Did you use the precompiled version? I am using the developer one, maybe thats the problem?

**Comment by kainpro** [comment]
> No tuve que cambiar nada y al hacer clic derecho -> cambiar el nombre de un archivo, aparece este modal:
> ![filegator_rename](https://user-images.githubusercontent.com/43741267/108716506-81136c80-751c-11eb-80ea-38320ab04cd7.jpg)
> 
> ¿Usó la versión precompilada? Estoy usando el desarrollador, ¿quizás ese es el problema?
> Además, me pregunto por qué el texto del botón es "Cerrar", el modal de la carpeta de selección solo muestra "Cerrar" en mi copia.

Hi Morph3us-net
I have downloaded the version v7.5.0 from the following link  https://docs.filegator.io/install.html 

Which version should I install?

**Comment by morph3us-net** [comment]
I am not affiliated with FileGator in any way, just trying to help somebody else out, while waiting for a response to my own issue.
I can not tell you what is right or wrong, I am just trying to find the problem with you.

This said, I am running 7.5.0, too. And it works for me.

Did you use it out of the box or are have you changed any of the code?
Does this occur on your online web server or a locally simulated server?
Have you made sure that you have PHP 7.2 or higher installed?

Maybe try to investigate yourself, open the developer console with CTRL + SHIFT + I and see if there are any error logs.

**Comment by kainpro** [comment]
problem solved i was using version 7.4.4.
