### ISSUE TITLE
Uploading big .exe files failes

### ISSUE THREAD

**Issue by Petje1972** [filegator/filegator#188]
Hello,

I am happy using Filegator for a while now but I got the following issue where uploading bigger .exe files (±150Mb) fail.
The uploading of the data chunks succeed (chunksize is set to default (1Mb)) but merging the multipart files takes forever and stops around 30Mb.
When uploading an MP4 file (200Mb) the merging of the multipart files is swift and takes around 2 second.

Have you ever experienced the issue?

The website is running on IIS.

Best regards
Petje1972

**Comment by alcalbg** [comment]
Hi,

I'm not using windows so I cannot try or confirm this. However, from your description above, I can only assume that some other process is involved here, maybe an antivirus or something similar which detects the executable and try to parse it. I suggest opening your task manager and looking at the cpu/memory consumption of the processes at the time of the actual merge.

Cheers

**Comment by Petje1972** [comment]
Thanks 4 the quick response.
I am going to check this out.
Keep up the good work!

Grtz P
