### ISSUE TITLE
How do i attach the s3 storage adapter?

### ISSUE THREAD

**Issue by larslight11** [filegator/filegator#19]
i looked at your documentation already , as well as the flysystems doc . i installed the ("composer require league/flysystem-aws-s3-v3"). But still am confused where to put the html code you gave in your doc , I tried putting it in the configuration.php file doesnt work.

can anyone help me try install the s3 adapter

**Comment by alcalbg** [comment]
You should replace these lines in your configuration.php :
```
        'Filegator\Services\Storage\Filesystem' => [
            'handler' => '\Filegator\Services\Storage\Filesystem',
            'config' => [
                'separator' => '/',
                'config' => [],
                'adapter' => function () {
                    return new \League\Flysystem\Adapter\Local(
                        __DIR__.'/repository'
                    );
                },
            ],
        ],
```
with this:
```
        'Filegator\Services\Storage\Filesystem' => [
            'handler' => '\Filegator\Services\Storage\Filesystem',
            'config' => [
                'separator' => '/',
                'config' => [],
                'adapter' => function () {
                    $client = new \Aws\S3\S3Client([
                        'credentials' => [
                            'key' => '123456',
                            'secret' => 'secret123456',
                        ],
                        'region' => 'us-east-1',
                        'version' => 'latest',
                    ]);

                    return new \League\Flysystem\AwsS3v3\AwsS3Adapter($client, 'my-bucket-name');
                },
            ],
        ],
```

**Comment by alcalbg** [comment]
Make sure you enter your own:

- key
- secret
- bucket name

If it doesn't work please check `/private/logs/app.log` to see what is the exact error

**Comment by larslight11** [comment]
i get this in my app,log , after replacing the code in the configuration.php and the configuration_sample.php file.

[2019-10-29 02:09:27] default.ALERT: Fatal Error (E_ERROR): Uncaught Error: Class 'Aws\S3\S3Client' not found in /root/filegator/configuration.php:80 Stack trac$

i feel like when i installed the {composer require league/flysystem-aws-s3-v3} it wasnt in the right directory maybe??

because on the AWS side i gave all the permissions already to my S3 Bucket.So i know its nothing from that side .

Also i tried attaching a SFTP Adapter same error in my app.log


Thank you for your help so far , but please help me try solve this it will be well appreciated bro.

**Comment by alcalbg** [comment]
The error message is clear, you don't have S3Client installed or you've installed it wrong.

Run this again in your filegator folder, where your configuration.php file is:

`composer require league/flysystem-aws-s3-v3`

**Comment by larslight11** [comment]
ok so i deleted the vendor folder inside my filegator folder installed  {composer require league/flysystem-aws-s3-v3} again , updated my configuration.php file 


![filegator1](https://user-images.githubusercontent.com/39655127/67752931-dea1c100-fa6e-11e9-8530-8b15b0909cb2.JPG)

![filegator2](https://user-images.githubusercontent.com/39655127/67752963-ea8d8300-fa6e-11e9-9780-e4041e2c4152.jpg)

![filegator3](https://user-images.githubusercontent.com/39655127/67752971-efeacd80-fa6e-11e9-90e6-cf18362af84c.JPG)


![filegator4](https://user-images.githubusercontent.com/39655127/67752989-f8db9f00-fa6e-11e9-836b-65b68c0de92f.JPG)


and i get an HTTP 500 and its not working

**Comment by alcalbg** [comment]
Put the original composer.json and composer.lock back and try in this order:

```
rm -Rf vendor/
composer install
composer require league/flysystem-aws-s3-v3

```

**Comment by larslight11** [comment]
ok done put the original composer.json and composer.lock back already 

then did this 
```
rm -Rf vendor/

then 

composer install
```

after composer install doesnt let me install {composer require league/flysystem-aws-s3-v3}


![filegator5](https://user-images.githubusercontent.com/39655127/67755340-f2e7bd00-fa72-11e9-9f5c-03e34a6fa1ea.JPG)

**Comment by alcalbg** [comment]
The error message is clear enough, you don't have enough memory for composer to do the update.

Ok, maybe we can trick composer with this:

- delete vendor folder `rm -Rf vendor/`
- remove composer.lock `rm composer.lock`
- open `composer.json` end make it look like this:
```
{
    "name": "filegator/filegator",
    "description": "Filegator",
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "monolog/monolog": "^1.24",
        "nikic/fast-route": "^1.3",
        "symfony/security-csrf": "^4.3",
        "symfony/http-foundation": "^4.2",
        "dibi/dibi": "^4.0",
        "php-di/php-di": "^6.0",
        "rakit/validation": "^1.1",
        "league/flysystem": "^1.0",
        "league/flysystem-ziparchive": "^1.0",
        "league/flysystem-aws-s3-v3": "^1.0"
    },
    "authors": [
        {
            "name": "Milos Stojanovic",
            "email": "alcalbg@gmail.com"
        }
    ],
    "autoload": {
        "psr-4": {
            "Filegator\\": "backend"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/backend/"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "^7.5",
        "symfony/var-dumper": "^4.2",
        "league/flysystem-memory": "^1.0",
        "phpstan/phpstan": "^0.11.8"
    }
}

```
- now run `composer install`

**Comment by larslight11** [comment]
ok bro it works now thanks love you ...i just had to swap memory for my composer to work
