### ISSUE TITLE
[Bug] Doesn't accept files with some special chars

### ISSUE THREAD

**Issue by TarantinoMariachi** [filegator/filegator#192]
**Describe the bug**
If I've a folder with an image with the char ã it gives an error and it doesn't open it.

**Expected behavior**
It should open the folder

**Logs**
`[2021-03-03 00:50:21] default.ALERT: Fatal Error (E_ERROR): Uncaught UnexpectedValueException: The Response content must be a string or object implementing __toString(), "boolean" given. in /home/public_html/forum/upload/vendor/symfony/http-foundation/Response.php:406 Stack trace: #0 /home/public_html/forum/upload/backend/Kernel/Response.php(23): Symfony\Component\HttpFoundation\Response->setContent(false) #1 /home/public_html/forum/upload/backend/Controllers/FileController.php(55): Filegator\Kernel\Response->json(Object(Filegator\Services\Storage\DirectoryCollection)) #2 [internal function]: Filegator\Controllers\FileController->changeDirectory(Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response)) #3 /home/public_html/forum/upload/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array) #4 /home/public_html/forum/upload/vendor/php-di/php-di/src/Container.php(276): Invoker\Invoker->call(Array, Array) #5 /home/public_html/forum/upload/backend/Services/Router/Router.php(78): DI\Container {"code":1,"message":"Uncaught UnexpectedValueException: The Response content must be a string or object implementing __toString(), \"boolean\" given. in /home/public_html/forum/upload/vendor/symfony/http-foundation/Response.php:406\nStack trace:\n#0 /home/public_html/forum/upload/backend/Kernel/Response.php(23): Symfony\\Component\\HttpFoundation\\Response->setContent(false)\n#1 /home/public_html/forum/upload/backend/Controllers/FileController.php(55): Filegator\\Kernel\\Response->json(Object(Filegator\\Services\\Storage\\DirectoryCollection))\n#2 [internal function]: Filegator\\Controllers\\FileController->changeDirectory(Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response))\n#3 /home/public_html/forum/upload/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array)\n#4 /home/public_html/forum/upload/vendor/php-di/php-di/src/Container.php(276): Invoker\\Invoker->call(Array, Array)\n#5 /home/public_html/forum/upload/backend/Services/Router/Router.php(78): DI\\Container","file":"/home/public_html/forum/upload/vendor/symfony/http-foundation/Response.php","line":406,"trace":null} []`

**Environment (please complete the following information):**
 - FileGator Version [7.5.0]
 - Server: [Apache 2.4 on Centos 7]
 - PHP Version [PHP 7.2]
 - Browser [Chrome]

**Comment by alcalbg** [comment]
Hi,

Your file names and paths must me encoded in UTF-8. I've just tried with the image named **ã.png** and it works fine. You can use utility called **convmv** to check and convert encodings.

To see if everything is UTF-8 encoded, open the console, go to this folder, and run:
```
convmv -f UTF-8 -t UTF-8 *
```

You can also try to make it work with different encoding as described here:
https://github.com/php/php-src/blob/PHP-7.1.0beta2/UPGRADING#L321

But from my experience, PHP does not work very well with non UTF-8 encodings.

![try](https://user-images.githubusercontent.com/1578476/109794895-a25c1300-7c16-11eb-8ad2-d7019f54f7c3.png)

**Comment by TarantinoMariachi** [comment]
Thank you, that solved it.
