### ISSUE TITLE
i have a problem!! 

### ISSUE THREAD

**Issue by kzhumberto19** [filegator/filegator#193]
;C

![image](https://user-images.githubusercontent.com/57538217/110165526-ac1d7c00-7db8-11eb-8eda-3d376b889a7f.png)

**Comment by alcalbg** [comment]
Hi,

Set the php error reporting to **default value** so it doesn't scream like that, see:

https://www.php.net/manual/en/function.error-reporting.php
https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting 

Or just add this line to the top of your index.php file:
```
<?php

// Turn off all error reporting
error_reporting(0);
```
