### ISSUE TITLE
Two consecutive periods in a filename cause problems.

### ISSUE THREAD

**Issue by Travilo** [filegator/filegator#202]
**Describe the bug**
If a filename contains two consecutive periods, the text editor shows strange contents and you can't delete the file.

**To Reproduce**
1. Create or upload a file named "Test.. 123.txt"
2. Click on the file to see... HTML? Where did that come from?
3. Try to delete the file... Unknown Error

**Logs**
`[2021-03-22 15:52:20] default.ALERT: Fatal Error (E_ERROR): Uncaught League\Flysystem\FileNotFoundException: File not found at path:  in /var/www/filegator/vendor/league/flysystem/src/Filesystem.php:389 Stack trace: #0 /var/www/filegator/vendor/league/flysystem/src/Filesystem.php(235): League\Flysystem\Filesystem->assertPresent('') #1 /var/www/filegator/backend/Services/Storage/Filesystem.php(123): League\Flysystem\Filesystem->delete('') #2 /var/www/filegator/backend/Controllers/FileController.php(167): Filegator\Services\Storage\Filesystem->deleteFile('/Test.. 123.txt') #3 [internal function]: Filegator\Controllers\FileController->deleteItems(Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response)) #4 /var/www/filegator/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array) #5 /var/www/filegator/vendor/php-di/php-di/src/Container.php(276): Invoker\Invoker->call(Array, Array) #6 /var/www/filegator/backend/Services/Router/Router.php(78): DI\Container->call(Array, Array) #7 /var/www/filegator/backend/App.php(33): Filegator\Services\Rou {"code":1,"message":"Uncaught League\\Flysystem\\FileNotFoundException: File not found at path:  in /var/www/filegator/vendor/league/flysystem/src/Filesystem.php:389\nStack trace:\n#0 /var/www/filegator/vendor/league/flysystem/src/Filesystem.php(235): League\\Flysystem\\Filesystem->assertPresent('')\n#1 /var/www/filegator/backend/Services/Storage/Filesystem.php(123): League\\Flysystem\\Filesystem->delete('')\n#2 /var/www/filegator/backend/Controllers/FileController.php(167): Filegator\\Services\\Storage\\Filesystem->deleteFile('/Test.. 123.txt')\n#3 [internal function]: Filegator\\Controllers\\FileController->deleteItems(Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response))\n#4 /var/www/filegator/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array)\n#5 /var/www/filegator/vendor/php-di/php-di/src/Container.php(276): Invoker\\Invoker->call(Array, Array)\n#6 /var/www/filegator/backend/Services/Router/Router.php(78): DI\\Container->call(Array, Array)\n#7 /var/www/filegator/backend/App.php(33): Filegator\\Services\\Rou","file":"/var/www/filegator/vendor/league/flysystem/src/Filesystem.php","line":389,"trace":null} []
`

**Environment:**
- FileGator Version: 7.5.0
- Server: Apache/2.4.38 (Debian)
- PHP Version: 7.3
- Browser: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by alcalbg** [comment]
Thanks for reporting this bug
