### ISSUE TITLE
CSRF token issue

### ISSUE THREAD

**Issue by llars0689** [filegator/filegator#203]
Good evening,

I have noticed in the app logs that im getting an error about an invalid csrf token. I had created a randomized csrf token in the configuration.php file, and i noticed that im getting the error below in the logs. I tried changing the token as well, but still get the same errors. It doesnt seem to affect the web portal and users can still login fine, but i see it pop up occiasionally.

[2021-03-21 19:05:37] default.ALERT: Fatal Error (E_ERROR): Uncaught Exception: Csrf token not valid in /var/www/filegator-st1/filegator/backend/Services/Security/Security.php:46

Stack trace: #0 /var/www/filegator-st1/filegator/backend/App.php(33): Filegator\Services\Security\Security->init(Array) #1 /var/www/filegator-st1/filegator/dist/index.php(53): Filegator\App->__construct(Object(Filegator\Config\Config), Object(Filegator\Kernel\Request), Object(Filegator\Kernel\Response), Object(Filegator\Kernel\StreamedResponse), Object(Filegator\Container\Container)) #2 {main}   thrown {"code":1,"message":"Uncaught Exception: Csrf token not valid in /var/www/filegator-st1/filegator/backend/Services/Security/Security.php:46\nStack trace:\n#0 /var/www/filegator-st1/filegator/backend/App.php(33): Filegator\\Services\\Security\\Security->init(Array)\n#1 /var/www/filegator-st1/filegator/dist/index.php(53): Filegator\\App->__construct(Object(Filegator\\Config\\Config), Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response), Object(Filegator\\Kernel\\StreamedResponse), Object(Filegator\\Container\\Container))\n#2 {main}\n  thrown","file":"/var/www/filegator-st1/filegator/backend/Services/Security/Security.php","line":46,"trace":null} []

**Comment by alcalbg** [comment]
This is fixed and it will be included in the next release
