### ISSUE TITLE
DockerHub

### ISSUE THREAD

**Issue by siddjellali** [filegator/filegator#206]
Hello team, 

Could you please provide and keep up-to-date a docker image / docker compose ?

Thanks

**Comment by kwilliams312** [comment]
I created an initial docker build for this, you're welcome to copy / use it as you wish

https://hub.docker.com/r/kwillia/filegator_docker

https://github.com/kwilliams312/filegator_docker_image

**Comment by siddjellali** [comment]
After a year working on CI and so on, it will be easier to create a CI and automate the workflow to push every release on dockerhub. @alcalbg Why don't you create a workflow dedicated on that with filegator account ?

**Comment by alcalbg** [comment]
Thanks everyone. Yes, CI pipeline would be the optimal solution. I am working on another project atm, will do that eventually.

**Comment by alcalbg** [comment]
Official Docker hub image is here:

https://hub.docker.com/r/filegator/filegator

TODO: automated build

**Comment by im-n1** [comment]
Any chance for arm support?

**Comment by alcalbg** [comment]
just added arm/v7 and arm64, can you try again?

https://hub.docker.com/r/filegator/filegator

**Comment by im-n1** [comment]
1. amazing fast response
2. sadly getting this error
```
Creating filegator ... done
Attaching to filegator
filegator    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.0.2. Set the 'ServerName' directive globally to suppress this message
filegator    | (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
filegator    | no listening sockets available, shutting down
filegator    | AH00015: Unable to open logs
filegator exited with code 1
```
I guess I'm probably missing some ENV vars but docker-compose nor Dockerfile in repo doesn't specify some.

**Comment by alcalbg** [comment]
Huh, this seems like some permissions issue. Can you try with root user or something?

**Comment by alcalbg** [comment]
Dockerhub CI workflow created, closing this now

**Comment by im-n1** [comment]
Sadly running uder root is not a solution. Since the error is from the container complaining about env var l would racommend to attach docker-compose file.

Also another "fast closing issue" l see :)

**Comment by alcalbg** [comment]
Check this https://github.com/filegator/filegator/blob/master/docker-compose.yml

I don't see complains about env vars, from your log it's permission issue. I could be wrong tho.

```
filegator    | (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
```

**Comment by alcalbg** [comment]
Anyone else with similar issues running this? On arm? As non-root? Help?
```
docker run -p 8888:80 filegator/filegator:v7.8.5-multiarch
```
http://localhost:8888

**Comment by im-n1** [comment]
How I said eadlier - the error is within the container so running the container as a root doesn't help.

```
odroidxu4:~:% docker run --rm -p 8883:80 filegator/filegator
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directi
ve globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
odroidxu4:~:% sudo docker run --rm -p 8883:80 filegator/filegator
[sudo] password for n1:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directi
ve globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```

**Comment by platypusgit** [comment]
I am getting the exact same error in v7.8.7.

**Comment by alcalbg** [comment]
Ok, can someone try one more time with arm please?

```docker run -p 8080:8080 filegator/filegator:v7.9.2-multiarch```

http://localhost:8080


ref: https://github.com/filegator/filegator/commit/37d25ef88152af5b0019f627905909bf8601ff56

**Comment by im-n1** [comment]
I'm able to start the service but sooner of later I'm getting `[Wed Jan 25 20:36:36.164049 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully` and it dies.

**Comment by alcalbg** [comment]
Yes, I've noticed this as well. It sounds stupid, but it happens when you resize your terminal window, hence the name of the signal - window change!

https://bz.apache.org/bugzilla/show_bug.cgi?id=50669

Anyway, this should not happen if you're using it as a normal service, with docker compose etc.

**Comment by im-n1** [comment]
Cannot confirm that. Havent resized the window term at all.

**Comment by alcalbg** [comment]
Are you getting the `SIGWINCH` if you detach it and run it as a background service?

```
docker run -d --name filegatorservice -p 8080:8080 filegator/filegator:v7.9.2-multiarch
docker logs filegatorservice -f
```

**Comment by im-n1** [comment]
Cannot explain that but the issue vanished. so i guess the whole `SIGWINCH` problem is gone.

I have 2 quick questions and 2 suggestions:

question a)  How do I completely disable auth? Tried to comment out Auth module in config - got fatal error. Ended up with giving all pesmissions to Guest and then delete Admin user.

question b) How to make run the whole thing under a different user but www-data? This is crucial for new files that are created by this tool.

suggestion a) Please state in docs that app root in container is `/var/www/filegator` so when one wants to use it's own config file via volumes he can add something like:
```yaml
volumes:
  - ./config/configuration.php:/var/www/filegator/configuration.php
```
This is very common among Docker images.

suggestion b) Plese state in docs that THE DIRECTORY Filegator is gonna manage sits under `/var/www/filegator/reporitory`. One can then do:
```yaml
volumes:
  - ./my_dir:/var/www/filegator/repository
```

Thanks in advance and my apologies if the suggestion stuff already are in docs and I overlooked them.

**Comment by alcalbg** [comment]
Giving all permissions to Guest is the way to disable auth. That's how it is done here: https://demo.filegator.io

To change the user you must customize the Dockerfile. However, file permissions for volumes and matching the uid/gid with host seems to be a huge mess. 

All the info related to Docker is now listed here: https://hub.docker.com/r/filegator/filegator
Suggestions are welcome.

**Comment by mleczakm** [comment]
Multiarch builds seems outdated, what is the reason?

**Comment by alcalbg** [comment]
The CI workflow is missing multiarch config/setup https://github.com/filegator/filegator/blob/master/.github/workflows/ci-dockerhub.yml

**Comment by zhan-py** [comment]
> Giving all permissions to Guest i

Hi, would you explain how to give all permissions to Guest? Thank you!

**Comment by alcalbg** [comment]
Automatic multiarch build added in #517

```docker pull filegator/filegator:latest-multiarch```

or specific version:

```docker pull filegator/filegator:v7.12.0-multiarch```
