### ISSUE TITLE
Digitalocean Spaces

### ISSUE THREAD

**Issue by irfanjunaid** [filegator/filegator#22]
Digitalocean Spaces storage adapter is not working. Facing 500 server error.

**To Reproduce:**
1. Download and extract the latest release
2. Run `composer require league/flysystem-aws-s3-v3`
3. Access the app
4. See 500 server error on browser

**Expected behavior:**
App loads fine and files should be stored on Digitalocean Spaces

**Logs:**
Webserver logs:

> PHP Fatal error:  Uncaught Error: Class 'Filegator\\App' not found in /var/www/html/dist/index.php:49
> 
> Stack trace:
> #0 {main}
> thrown in /var/www/html/dist/index.php on line 49

**Environment:**
 - FileGator Version: 7.1.2
 - Server: Apache 2.4 on Ubuntu server 18.04
 - PHP Version: 7.2
 - Browser: Chrome, Firefox

**Additional context:**
The app works fine when we extract and use it directly without any changes. The error is encountered only after installing the composer package.

**Comment by alcalbg** [comment]
Hi,

Thank you for reporting this. 

I've included composer and npm files to precompiled build so that you can add storage adapters with this version as well. Can you please download the latest zip file and try again https://docs.filegator.io/install.html

**Comment by irfanjunaid** [comment]
I can confirm this worked perfectly and files are saved to Digitalocean spaces correctly. It installed a lot of packages by the way than before. Not sure if its okay to ignore the warning on php-parse.

> Using version ^1.0 for league/flysystem-aws-s3-v3
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 54 installs, 0 updates, 0 removals
>   - Installing ocramius/package-versions (1.4.0): Downloading (100%)         
>   - Installing mtdowling/jmespath.php (2.4.0): Loading from cache
>   - Installing guzzlehttp/promises (v1.3.1): Loading from cache
>   - Installing ralouphie/getallheaders (3.0.3): Loading from cache
>   - Installing psr/http-message (1.0.1): Loading from cache
>   - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
>   - Installing guzzlehttp/guzzle (6.4.1): Loading from cache
>   - Installing aws/aws-sdk-php (3.112.33): Downloading (100%)         
>   - Installing league/flysystem-aws-s3-v3 (1.0.23): Loading from cache
>   - Installing sebastian/version (2.0.1): Loading from cache
>   - Installing sebastian/resource-operations (2.0.1): Loading from cache
>   - Installing sebastian/recursion-context (3.0.0): Loading from cache
>   - Installing sebastian/object-reflector (1.1.1): Loading from cache
>   - Installing sebastian/object-enumerator (3.0.3): Loading from cache
>   - Installing sebastian/global-state (2.0.0): Loading from cache
>   - Installing sebastian/exporter (3.1.0): Downloading (100%)         
>   - Installing sebastian/environment (4.2.2): Loading from cache
>   - Installing sebastian/diff (3.0.2): Loading from cache
>   - Installing sebastian/comparator (3.0.2): Loading from cache
>   - Installing phpunit/php-timer (2.1.2): Loading from cache
>   - Installing phpunit/php-text-template (1.2.1): Loading from cache
>   - Installing phpunit/php-file-iterator (2.0.2): Loading from cache
>   - Installing theseer/tokenizer (1.1.3): Loading from cache
>   - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
>   - Installing phpunit/php-token-stream (3.0.1): Downloading (100%)         
>   - Installing phpunit/php-code-coverage (6.1.4): Loading from cache
>   - Installing symfony/polyfill-ctype (v1.11.0): Downloading (100%)         
>   - Installing webmozart/assert (1.4.0): Loading from cache
>   - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
>   - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
>   - Installing phpdocumentor/reflection-docblock (4.3.1): Loading from cache
>   - Installing doctrine/instantiator (1.2.0): Loading from cache
>   - Installing phpspec/prophecy (1.8.1): Loading from cache
>   - Installing phar-io/version (2.0.1): Loading from cache
>   - Installing phar-io/manifest (1.0.3): Loading from cache
>   - Installing myclabs/deep-copy (1.9.1): Downloading (100%)         
>   - Installing phpunit/phpunit (7.5.12): Downloading (100%)         
>   - Installing symfony/var-dumper (v4.3.1): Downloading (100%)         
>   - Installing league/flysystem-memory (1.0.2): Downloading (100%)         
>   - Installing symfony/finder (v4.3.1): Downloading (100%)         
>   - Installing symfony/polyfill-php73 (v1.11.0): Downloading (100%)         
>   - Installing symfony/console (v4.3.1): Downloading (100%)         
>   - Installing phpstan/phpdoc-parser (0.3.5): Downloading (100%)         
>   - Installing nette/utils (v3.0.1): Downloading (100%)         
>   - Installing nette/schema (v1.0.0): Downloading (100%)         
>   - Installing nette/finder (v2.5.0): Downloading (100%)         
>   - Installing nette/robot-loader (v3.2.0): Downloading (100%)         
>   - Installing nette/php-generator (v3.2.2): Downloading (100%)         
>   - Installing nette/neon (v3.0.0): Downloading (100%)         
>   - Installing nette/di (v3.0.0): Downloading (100%)         
>   - Installing nette/bootstrap (v3.0.0): Downloading (100%)         
>   - Installing jean85/pretty-package-versions (1.2): Downloading (100%)         
>   - Installing composer/xdebug-handler (1.3.3): Downloading (100%)         
>   - Installing phpstan/phpstan (0.11.8): Downloading (100%)         
> guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
> aws/aws-sdk-php suggests installing doctrine/cache (To use the DoctrineCacheAdapter)
> aws/aws-sdk-php suggests installing aws/aws-php-sns-message-validator (To validate incoming SNS notifications)
> sebastian/global-state suggests installing ext-uopz (*)
> phpunit/phpunit suggests installing phpunit/php-invoker (^2.0)
> phpunit/phpunit suggests installing ext-soap (*)
> symfony/console suggests installing symfony/event-dispatcher
> symfony/console suggests installing symfony/lock
> symfony/console suggests installing symfony/process
> nette/bootstrap suggests installing tracy/tracy (to use Configurator::enableTracy())
> Writing lock file
> Generating autoload files
>     Skipped installation of bin bin/php-parse for package nikic/php-parser: file not found in package
> ocramius/package-versions:  Generating version class...
> ocramius/package-versions: ...done generating version class

**Comment by alcalbg** [comment]
Looks good, you can ignore that warning.

Closing this now, cheers!

**Comment by irfanjunaid** [comment]
Thanks a lot for your timely help! This app is really useful :-)
