### ISSUE TITLE
Change local repository folder outside web root

### ISSUE THREAD

**Issue by evensenservice** [filegator/filegator#221]
How do i change __DIR__.'/repository' to example "c:\server\files", when my filegator webroot folder is "C:\server\webhost\filegator"
Apache&PHP7 on Windows

And do someone have a good way of implementing reCAPTCHA v2 or v3?

**Comment by alcalbg** [comment]
Hi,

Try with absolute path, something like "/server/files/".

See #114

**Comment by evensenservice** [comment]
Hi! I tried this every way i could. I found out that if i make a new webhost folder for filegator like c:\serve, and then i simply just put __DIR__.'R' in config file, then my filegator would make c:\server as my new repository folder. This is the only way i could get my repository folder outside the webroot folder for filegator.
