### ISSUE TITLE
Bug report: Missing text when language is not set

### ISSUE THREAD

**Issue by tobiasgruber1995** [filegator/filegator#230]
**Describe the bug**

I tried to set the language dynamically. Along the way I realized that if the `language` field in `frontend_config` in `configuration.php` is for some reason empty/null, the app still works and english is chosen as default language. But: For some reason, not all the texts seem to be set. I did not check in detail, but for example the pagination or the `Selected: ... of ...` does not work properly/is missing text.

**To reproduce**

1. Set `language` in `frontend_config` in `configuration.php` to an empty string/null
2. Open Filegator
3. See error

**Expected behavior**

All the texts should be set the same way as when the language is set to english.

**Environment**

 - FileGator Version: 7.5.2
 - Server: Apache 2.4.41 on Debian Linux
 - PHP Version: PHP 7.4
 - Browser: Chrome, Firefox

**Comment by alcalbg** [comment]
Hi,

The `language` field must be set to valid language string from https://docs.filegator.io/translations/default.html, it can't be empty/null.

Cheers

**Comment by tobiasgruber1995** [comment]
Hi,

well, if that is the case then the application should not start at all/log the user out/throw an `Unexpected Error` or something, or? 

Of course considering normal usage `language` should not be empty/null. However, if that case occurs by accident, then the application should either do one of the options above **or** set `language` to a default value, for example english. Which it apparently kind of does, only not completely, so at the moment it looks pretty weird if the application starts and works normally, but some of the texts are missing.

Cheers
