### ISSUE TITLE
Bug report: Missing `SameSite` attribute in cookie `filegator`

### ISSUE THREAD

**Issue by tobiasgruber1995** [filegator/filegator#232]
**Describe the bug**

The cookie containing the session ID (`filegator`) is missing the `SameSite` attribute. That might cause the cookie to be rejected on some browsers.

**To Reproduce**

1. Open Filegator
2. Open developer tools
3. Open console

**Expected behavior**

The SameSite attribute should be set.

**Logs**

JavaScript error message:

Cookie “filegator" will soon be rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite” attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.

**Environment**

 - FileGator Version: 7.5.2
 - Server: Apache 2.4.41 on Debian Linux
 - PHP Version: PHP 7.4
 - Browser: Chrome, Firefox

**Additional context**

There are different options for the attribute: `Lax`, `None` and `Strict`. The default option is `Lax`, and I recommend keeping that. I tried setting it to `Strict`, but that causes an automatic logout on page reload.

**Comment by alcalbg** [comment]
Hi,

You can configure session details in your `configuration.php` file:

```
        'Filegator\Services\Session\SessionStorageInterface' => [               
            'handler' => '\Filegator\Services\Session\Adapters\SessionStorage', 
            'config' => [                                                       
                'handler' => function () {                                      
                    $save_path = null; // use default system path               
                    //$save_path = __DIR__.'/private/sessions';                 
                    $handler = new \Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler($save_path);
                                                                                
                    return new \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage([
                            "cookie_samesite" => "None",                        
                            "cookie_secure" => true                             
                        ], $handler);                                           
                },                                                              
            ],                                                                  
        ],    
```

Hope this helps.

Cheers!

**Comment by tobiasgruber1995** [comment]
Hi,

I know I can set it there and already did. My recommendation to you was to add that by default to the configuration since until now it is not part of it, because even if no other cookies are set by a user, by default at least the `filegator` cookie containing the session ID is set and does not have the `SameSite` attribute - and according to the error displayed in the console that will be rejected in future releases and therefore cause your application to stop working.

If a user removes it and then has problems - well, then he has to figure it out himself. But by default the application should be working, and for that you will need to add those settings.

Cheers!

**Comment by alcalbg** [comment]
Ok, this make sense. What would be the sensible configuration defaults here?

**Comment by tobiasgruber1995** [comment]
- Considering `SameSite`: there are different options for the attribute - `Lax`, `None` and `Strict`. The default option is `Lax`, and I recommend keeping that. I tried setting it to `Strict`, but that causes an automatic logout on page reload.
- Considering `Secure`: I did not encounter any negative effects from setting them to secure, so I would recommend to do that.

**Comment by alcalbg** [comment]
I think `Secure` should not be set as default, if this is set to true, it will only work with `https` or `localhost` sites.

Which leave us with this:
```
                    return new \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage([
                            "cookie_samesite" => "Lax",
                        ], $handler);  
```

**Comment by tobiasgruber1995** [comment]
Alright, sounds good :+1:
