### ISSUE TITLE
Bug report: Search function is causing problems

### ISSUE THREAD

**Issue by tobiasgruber1995** [filegator/filegator#234]
**Describe the bug**

When using the search function, many parallel running PHP processes are opened to search recursively. Depending on the amount of processes, that can cause a server to crash.

**To Reproduce**

1. Open Filegator
2. Search for a file
3. See error

**Expected behavior**

Only submit the folder to be searched in and then from there search recursively within the same PHP process.

**Environment**

 - FileGator Version: 7.5.2
 - Server: Apache 2.4.41 on Debian Linux
 - PHP Version: PHP 7.4
 - Browser: Chrome, Firefox

**Comment by alcalbg** [comment]
Hi,

I'm not sure if this is a bug or a feature :)

I will leave this open for discussion...

**Comment by tobiasgruber1995** [comment]
Hi,

well, I can only tell you that it caused my server to crash once too many processes were running parallel due to a bigger directory - and then I had to build a workaround. In my eyes something that can cause a server to crash while using a normal function definitely should be considered a bug :)

**Comment by alcalbg** [comment]
I agree, it should have some kind of configurable limit how many parallel processes is allowed to run on each search.

**Comment by tobiasgruber1995** [comment]
That would also be a good solution. What do you think about my proposed one?

**Comment by alcalbg** [comment]
Well, if we make this configurable, your solution can be achieved with `search_simultaneous=1` which basically disables any parallelism. Right?

**Comment by tobiasgruber1995** [comment]
Yes, I think that should work :+1:

**Comment by alcalbg** [comment]
Can you please check the latest commit?

**Comment by tobiasgruber1995** [comment]
Looks good :+1:
