### ISSUE TITLE
Bug report: Deleting a folder does not delete symlinks

### ISSUE THREAD

**Issue by tobiasgruber1995** [filegator/filegator#242]
**Describe the bug**
When deleting a folder, symlinks are not deleted which causes the folder itself to not be deleted.

E.g.: Let's say there is a folder with 10 files, one a symlink and 9 not. Deleting the folder via Filegator will cause the 9 files to be deleted but the symlink will just stay as it is, causing the folder to not be deleted either.

**To Reproduce**
1. Create a folder
2. Create one normal file and one symlink within the folder
3. Click 'Delete'
4. The folder should still appear
5. Open the folder - you will see that the normal file was removed, but the symlink still exists

**Expected behavior**
Deleting a folder should also delete symlinks.

**Environment**
 - FileGator Version: 7.6.0
 - Server: Apache 2.4.41 on Ubuntu
 - PHP Version: PHP 7.4
 - Browser: Chrome, Firefox

**Comment by alcalbg** [comment]
Unfortunately, symlinks are not supported by underlying Flysystem adapters thephpleague/flysystem#599
