### ISSUE TITLE
Feature Request: Upload folder

### ISSUE THREAD

**Issue by github-canni** [filegator/filegator#25]
- [ ] Allow uploading whole folders via Drag & Drop or "Add Files"-function

**Comment by MACscr** [comment]
Ah man, i need this too. Didnt realize it was needed until the client informed me AFTER of course i got this setup and branded for their print shop. Doh!

**Comment by github-canni** [comment]
@MACscr 
Maybe team could implement that as "select a folder" which gets zipped, uploaded and unzipped.

You can upload a ZIP, use Filegators UNZIP Function.
Guess you also need to comment out lines

39-41 in function "createDir"
/*while (! empty($this->storage->listContents($destination, true))) {
            $destination = $this->upcountName($destination);
        }*/

50-52 in function "createFile"
/*while ($this->storage->has($destination)) {
            $destination = $this->upcountName($destination);
        }*/

Then unzipping feature of filegator will overwrite if folders/subfolders and files are already existing. Quick tested for local adapter. No warrenty!

**Comment by MACscr** [comment]
Why add that type of overhead? Compression takes cpu cycles that isn’t really needed for the situation. Browser api’s can handle multiple uploaded files just fine.

- Mark

**Comment by github-canni** [comment]
@MACscr
Just as suggestion as it'd would be quickly implemented with current code, not sure how fast they could get recursively upload feature done though I surely would appreciate that too of course :)

**Comment by Barctic** [comment]
With major browsers now supporting `webkitdirectory` this enhancement should start to be easier to implement.

`<input type="file" webkitdirectory directory multiple />` is surprisingly powerful for directory uploads. Code would have to be refactored to support though.

Here is the latest browser support on the feature. https://caniuse.com/#feat=input-file-directory

**Comment by alcalbg** [comment]
This feature has been implemented in #147. Can someone please try it out with the latest filegator? Thanks!

**Comment by Meuschke23** [comment]
For me, it works on Firefox 82.0.2 👍 and the latest FileGator.
