### ISSUE TITLE
Readable URLs?

### ISSUE THREAD

**Issue by MACscr** [filegator/filegator#26]
Looking to be able to easily recognize urls when pasting a few of them in an email. Since its dynamically generating the urls, its impossible to know what file it is when going back through emails or going through a list. Possible to list the filename in it?

**Comment by Daryadi-S** [comment]
I also agree. Why not just add another menu on the file option "copy direct link".

This is useful especially for images to use for a readable link in HTML `<img src="http://example.com/uploadfolder/image-of-something.png" />`.

**Comment by mhh-hno** [comment]
Direct links, or either links displaying the file itself instead of starting a download, would also be very handy for us. The random-URL could still be used - but an option for "Copy link" would be great.

**Comment by MacGurk** [comment]
This feature would be very helpful, as I would like to use this as a web based company share to access images and other files directly over the URL to be embedded in Jira tickets or emails without downloading.
It could be an additional option like "copy direct link" or maybe as a global setting to switch between the two styles.

**Comment by alcalbg** [comment]
Let's group all sharing feature requests here
https://github.com/filegator/filegator/issues/6
