### ISSUE TITLE
File/folder permissions per user

### ISSUE THREAD

**Issue by LippiLpn** [filegator/filegator#263]
Hello, is there any way to setup file/folder permissions per user?
I wish I could make visible file1.txt for user X and not visible for user Y.

Thank for Your response.

**Comment by alcalbg** [comment]
Not in the same folder. You can only have two different folders for two users.

**Comment by LippiLpn** [comment]
Can You explain how to do it?

**Comment by alcalbg** [comment]
Sure,

- log in as admin and create two folders, folder1 and folder2, you can also put some files in both folders
- then, create your first user user1 and set his home folder to folder1
- create your second user and set his home folder to folder2
- logout admin and try with users
