### ISSUE TITLE
overwrite file

### ISSUE THREAD

**Issue by 3pac-byte** [filegator/filegator#27]
Hi

I have the download filegator, and have it set up on my site.
I want when a file uploads that it overwrites the old one.
I have looked in your FAQ but cannot find the file "upload.class.php" which is mentioned in the FAQ

Is there a way I can force the uploaded file to overwrite the current file of the same name?
Small code customization is required for this, inside include/blueimp/server/php/upload.class.php 

replace this:
$file_name = $this->upcount_name($file_name);

with this:
unlink($this->options['upload_dir'].$file_name);

**Comment by alcalbg** [comment]
Hi, check if #8 helps

**Comment by 3pac-byte** [comment]
i tried and looked in # 8
If it doesn't work, I find lines 168 - 170 in \ backend \ Services \ Storage \ Filesystem.php


It says
/ * while ($ this-> storage-> has ($ destination)) {$ destination = $ this-> upcountName ($ destination); } * /


What does it need to do to overwrite files instead of creating a new one eg file name (1) .jpg

**Comment by alcalbg** [comment]
Have you tried with simply removing lines 168-170?

**Comment by github-canni** [comment]
@3pac-byte 
Which Filegator version do you use? Which Adapter do you use?

If you use latest version of Filegator and local adapter, go find the folder \backend\Services\Storage\Filesystem.php and comment out or remove lines 168 - 170.

**Comment by alcalbg** [comment]
please continue here #8
