### ISSUE TITLE
[Bug] Last version hasn't been tagged

### ISSUE THREAD

**Issue by jaapmarcus** [filegator/filegator#270]
**Describe the bug**
The last version has not been tagged as it has been done in the past.

https://github.com/filegator/filegator/releases/tag/untagged-7bc66f807d09dd18e633 Instead of 

As we currently use https://github.com/filegator/filegator/releases/download/v${fm_v}/filegator_v${fm_v}.zip it breaks  the last download version. 

Allowing the use of tagging allows us to select an older version if needed.

Best regards...

**Comment by alcalbg** [comment]
Can you try again please?

**Comment by jaapmarcus** [comment]
Thanks works fine :)
