### ISSUE TITLE
Enabling Private Repos results in fatal error

### ISSUE THREAD

**Issue by Timbo1966** [filegator/filegator#271]
Enabling this setting in configuration.php:
'private_repos' => true,

Results in this error:
Fatal error: Uncaught Error: Call to a member function setHomedir() on array in /usr/local/apache2/htdocs/filegator/backend/Services/Auth/Adapters/LDAP.php:213 Stack trace: #0 /usr/local/apache2/htdocs/filegator/backend/Services/Auth/Adapters/LDAP.php(113): Filegator\Services\Auth\Adapters\LDAP->getUsers() #1 /usr/local/apache2/htdocs/filegator/backend/Services/Auth/Adapters/LDAP.php(124): Filegator\Services\Auth\Adapters\LDAP->find('guest') #2 /usr/local/apache2/htdocs/filegator/backend/Services/Router/Router.php(33): Filegator\Services\Auth\Adapters\LDAP->getGuest() #3 /usr/local/apache2/htdocs/filegator/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(143): Filegator\Services\Router\Router->__construct(Object(Filegator\Kernel\Request), Object(Filegator\Services\Auth\Adapters\LDAP), Object(Filegator\Container\Container)) #4 /usr/local/apache2/htdocs/filegator/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectD in /usr/local/apache2/htdocs/filegator/backend/Services/Auth/Adapters/LDAP.php on line 213

I'm using v7.6.0.

**Comment by alcalbg** [comment]
ping @ahaenggli

**Comment by Timbo1966** [comment]
@ahaenggli

**Comment by ahaenggli** [comment]
Ups, when did I broke that... I'll add a PR.

private_repos works the same way as in the WordPress-Auth option: 
`each user will have its own sub folder, admin will see everything`

The `RepoPath` is the root folder. In there a sub folder for each user is created. 
Someone with direct filesystem access will also see everything.

**Comment by Timbo1966** [comment]
Can I have it both ways?  Private folders for each user plus a public folder that everyone can access?
Thanks for the quick response!

**Comment by ahaenggli** [comment]
No, that's not possible by the filegator configuration. If you are using a linux fileserver in the background, you could try to manually add a symlink to your "public" shared folder. Something structured like this
```
repo\
repo\public
repo\userA
repo\userA\public -> \repo\public
repo\userB
repo\userB\public -> \repo\public
```

**Comment by Timbo1966** [comment]
symlink doesn't seem to work

[root@files repository]# ls -l
drwxr-xr-x 3 apache apache 20 Sep 30 20:10 public
drwxr-xr-x 2 apache apache 52 Sep 30 20:11 tschroeder
drwxr-xr-x 2 apache apache 42 Sep 30 20:09 tschroedertest

[root@files repository]# ls tschroeder -l
lrwxrwxrwx 1 apache apache     10 Sep 30 20:11 public -> ../public/
-rw-r--r-- 1 apache apache 211513 Sep 30 20:02 tschroeder_priv_file.jpg

[root@files tschroedertest]# ls -l
total 208
lrwxrwxrwx 1 apache apache     10 Sep 30 20:15 public -> ../public/
-rw-r--r-- 1 apache apache 211513 Sep 30 20:02 tschroedertest_priv_file.jpg

When I put a symlink in each private folder and log in I just get "Unknown Error" in a red box

**Comment by alcalbg** [comment]
Thanks @ahaenggli  

Symlinks are not supported: https://github.com/filegator/filegator#limitations

**Comment by Bortus-AI** [comment]
> 'private_repos' => true

Thats sad to hear. Users should be allowed to share publicly if we allow it.

**Comment by Bortus-AI** [comment]
looks like maybe it's possible in the latest version https://flysystem.thephpleague.com/docs/adapter/local/
