### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Pilly170** [filegator/filegator#285]
**Describe the bug**
Unable to connect AWS S3 Bucket

**Logs**
[2021-12-04 11:07:47] default.ALERT: Fatal Error (E_ERROR): Uncaught Error: Class 'Aws\S3\S3Client' not found in /var/www/filegator/configuration.php:110 Stack trace: #0 /var/www/filegator/backend/Services/Storage/Filesystem.php(32): {closure}() #1 /var/www/filegator/backend/App.php(33): Filegator\Services\Storage\Filesystem->init() #2 /var/www/filegator/dist/index.php(53): Filegator\App->__construct() #3 {main}   thrown {"code":1,"message":"Uncaught Error: Class 'Aws\\S3\\S3Client' not found in /var/www/filegator/configuration.php:110\nStack trace:\n#0 /var/www/filegator/backend/Services/Storage/Filesystem.php(32): {closure}()\n#1 /var/www/filegator/backend/App.php(33): Filegator\\Services\\Storage\\Filesystem->init()\n#2 /var/www/filegator/dist/index.php(53): Filegator\\App->__construct()\n#3 {main}\n  thrown","file":"/var/www/filegator/configuration.php","line":110,"trace":null} []

**Environment (please complete the following information):**
 - FileGator Version - 7.7
 - Server:AWS Instance - Ubuntu 20.04 (S3 role applied to instance)
 - PHP Version 7.4.3

Installed as per instructions

Updated to composer 2
within /var/www/filegator
        ` sudo composer require league/flysystem-aws-s3-v3 -W       (cant without sudo)`

commented out current filesystem in /var/www/filegator/configuration.php

Added
```
        'Filegator\Services\Storage\Filesystem' => [
            'handler' => '\Filegator\Services\Storage\Filesystem',
            'config' => [
                'separator' => '/',
                'config' => [],
                'adapter' => function () {
                    $client = new \Aws\S3\S3Client([
                        'region' => 'eu-west-1',
                        'version' => 'latest',
                    ]);

                    return new \League\Flysystem\AwsS3v3\AwsS3Adapter($client, 'storagebucket');
                },
            ],
        ],
```

As the ec2 has the s3 role  says dont need credentials.

Any ideas?

**Comment by alcalbg** [comment]
Hi,

This looks like a composer issue. Try installing the S3 dependency with:

```
composer require league/flysystem-aws-s3-v3:^1.0
```

Let me know if it works so I can update the docs.

**Comment by Pilly170** [comment]
I'll have a go in a few hours. 
but anthing like this on AWS requires sudo

Was the config setting ok though?

**Comment by alcalbg** [comment]
I never tried without a credentials section, but you will definitively see a different error if that fails.

**Comment by Pilly170** [comment]
`buntu@ip-10-131-129-44:~$ composer require league/flysystem-aws-s3-v3:^1.0
./composer.json has been updated
Running composer update league/flysystem-aws-s3-v3
Loading composer repositories with package information
^X^X^XUpdating dependencies
Lock file operations: 15 installs, 0 updates, 0 removals
  - Locking aws/aws-crt-php (v1.0.2)
  - Locking aws/aws-sdk-php (3.208.1)
  - Locking guzzlehttp/guzzle (7.4.0)
  - Locking guzzlehttp/promises (1.5.1)
  - Locking guzzlehttp/psr7 (2.1.0)
  - Locking league/flysystem (1.1.8)
  - Locking league/flysystem-aws-s3-v3 (1.0.29)
  - Locking league/mime-type-detection (1.9.0)
  - Locking mtdowling/jmespath.php (2.6.1)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking symfony/deprecation-contracts (v2.5.0)
  - Locking symfony/polyfill-mbstring (v1.23.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 15 installs, 0 updates, 0 removals
  - Downloading aws/aws-crt-php (v1.0.2)
  - Downloading symfony/deprecation-contracts (v2.5.0)
  - Downloading psr/http-message (1.0.1)
  - Downloading psr/http-client (1.0.1)
  - Downloading ralouphie/getallheaders (3.0.3)
  - Downloading psr/http-factory (1.0.1)
  - Downloading guzzlehttp/psr7 (2.1.0)
  - Downloading guzzlehttp/promises (1.5.1)
  - Downloading guzzlehttp/guzzle (7.4.0)
  - Downloading league/mime-type-detection (1.9.0)
  - Downloading league/flysystem (1.1.8)
  - Downloading symfony/polyfill-mbstring (v1.23.1)
  - Downloading mtdowling/jmespath.php (2.6.1)
  - Downloading aws/aws-sdk-php (3.208.1)
  - Downloading league/flysystem-aws-s3-v3 (1.0.29)
  - Installing aws/aws-crt-php (v1.0.2): Extracting archive
  - Installing symfony/deprecation-contracts (v2.5.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing guzzlehttp/psr7 (2.1.0): Extracting archive
  - Installing guzzlehttp/promises (1.5.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.4.0): Extracting archive
  - Installing league/mime-type-detection (1.9.0): Extracting archive
  - Installing league/flysystem (1.1.8): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.23.1): Extracting archive
  - Installing mtdowling/jmespath.php (2.6.1): Extracting archive
  - Installing aws/aws-sdk-php (3.208.1): Extracting archive
  - Installing league/flysystem-aws-s3-v3 (1.0.29): Extracting archive
17 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
7 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
`
`[2021-12-06 14:23:54] default.ALERT: Fatal Error (E_ERROR): Uncaught Error: Class 'Aws\S3\S3Client' not found in /var/www/filegator/configuration.php:93 Stack trace: #0 /var/www/filegator/backend/Services/Storage/Filesystem.php(32): {closure}() #1 /var/www/filegator/backend/App.php(33): Filegator\Services\Storage\Filesystem->init() #2 /var/www/filegator/dist/index.php(53): Filegator\App->__construct() #3 {main}   thrown {"code":1,"message":"Uncaught Error: Class 'Aws\\S3\\S3Client' not found in /var/www/filegator/configuration.php:93\nStack trace:\n#0 /var/www/filegator/backend/Services/Storage/Filesystem.php(32): {closure}()\n#1 /var/www/filegator/backend/App.php(33): Filegator\\Services\\Storage\\Filesystem->init()\n#2 /var/www/filegator/dist/index.php(53): Filegator\\App->__construct()\n#3 {main}\n  thrown","file":"/var/www/filegator/configuration.php","line":93,"trace":null} []`

**Comment by Pilly170** [comment]
to what? they are currently 
sudo chown -R www-data:www-data filegator/
sudo chmod -R 775 filegator/

As per the install instructions?

**Comment by alcalbg** [comment]
This is not a file path, this is a namespace\class scheme as per psr-4 autoload specification.
```
\<NamespaceName>(\<SubNamespaceNames>)*\<ClassName>
```
When you install a package, composer will do the magic, autoload files, and resolve everything for you.

**Comment by Phil-ThePower-Pearce** [comment]
Ok, I think we've hit an impass. It doesnt seem to work with S3 with the current install instructions.
I'm not sure where to go with this without assistance.

**Comment by alcalbg** [comment]
Sorry, I have no idea what could be wrong here. I've just tried with fresh debian 11 following the current instructions, see https://vimeo.com/654054134

**Comment by Pilly170** [comment]
I literally copied you instruction for instruction from that video.
Soon as I saved the configuration.php with the AWS part, I get "This page isn’t working"

`[2021-12-07 17:36:44] default.ALERT: Fatal Error (E_ERROR): Uncaught Error: Class 'Aws\S3\S3Client' not found in /var/www/filegator/configuration.php:93 Stack trace: #0 /var/www/filegator/backend/Services/Storage/Filesystem.php(32): {closure}() #1 /var/www/filegator/backend/App.php(33): Filegator\Services\Storage\Filesystem->init() #2 /var/www/filegator/dist/index.php(53): Filegator\App->__construct() #3 {main}   thrown {"code":1,"message":"Uncaught Error: Class 'Aws\\S3\\S3Client' not found in /var/www/filegator/configuration.php:93\nStack trace:\n#0 /var/www/filegator/backend/Services/Storage/Filesystem.php(32): {closure}()\n#1 /var/www/filegator/backend/App.php(33): Filegator\\Services\\Storage\\Filesystem->init()\n#2 /var/www/filegator/dist/index.php(53): Filegator\\App->__construct()\n#3 {main}\n  thrown","file":"/var/www/filegator/configuration.php","line":93,"trace":null} []
`

Only difference was Im using Ubuntu 20.04 on AWS fully patched (update & dist-upgrade before install), and I pasted each command in separatly and you were logged in as root whereas I can only login as ubuntu.

**Comment by Pilly170** [comment]
Thanks for that. I did follow you command for command and it failed as before.

It was only after I noticed you were root for everything. When using AWS, I could only be ubuntu and it didnt seem to work just prefixing the commands with sudo.

This is my notes for AWS ubuntu

```
<create AWS policy>
    {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1420044805001",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:ReplicateObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::your-bucket-name",
                "arn:aws:s3:::your-bucket-name/*"
            ]
        }
    ]
}
<create AWS Role attaching AWS policy as above>
<create relevant AWS Security Groups>
<launch Instance with AWS IAM Role/Security Groups as above>

ssh to instance
sudo su
apt update && dist-upgrade
reboot
apt install -y wget unzip php apache2 php-cli libapache2-mod-php php-zip net-tools php-simplexml php-xml php-mbstring


cd /var/www/
wget https://github.com/filegator/static/raw/master/builds/filegator_latest.zip
unzip filegator_latest.zip && rm filegator_latest.zip

nano /etc/apache2/sites-available/filegator.conf
<VirtualHost *:80>
    DocumentRoot /var/www/filegator/dist
</VirtualHost>
<VirtualHost *:443>
    DocumentRoot /var/www/filegator/dist
</VirtualHost>

a2dissite 000-default.conf
a2ensite filegator.conf
systemctl restart apache2

chown -R www-data:www-data filegator/
chmod -R 775 filegator/

curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
HASH=`curl -sS https://composer.github.io/installer.sig`
php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

nano configuration.php
    Add AWS Section
        change bucketname
        Remove credentials section leaving region/version

composer require league/flysystem-aws-s3-v3:^1.0 -W
```

**Comment by alcalbg** [comment]
Great! Thanks for sharing your findings. I will try this myself once the us-east-1 recovers from the outage.
