### ISSUE TITLE
upload big file got 400 error

### ISSUE THREAD

**Issue by linlih** [filegator/filegator#290]
**Describe the bug**
install filegator in ubuntu 20.04, using nginx 1.18.0 verison and php8.0-fpm, change the parameter by https://filegator.io/faq/, but it still got 400 error, i change the server to apache2 got same error.

**To Reproduce**
upload big file, such 2GB or bigger

**Expected behavior**
upload success

**Screenshots**

**Logs**
If applicable, add relevant FileGator logs entries from ```/private/logs/app.log``` or web server logs.

**Environment (please complete the following information):**
 - FileGator Version 7.7.0
 - Server: nginx 1.18
 - PHP Version 8.0
 - Browser edge

**Additional context**

**Comment by linlih** [comment]
/private/logs/app.log didn't print out any error info

**Comment by alcalbg** [comment]
This is most likely server-side error, misconfiguration or some proxy restriction. Also, that faq is not relevant for this version of filegator.

**Comment by linlih** [comment]
Thanks for the reply, Fix it by change server side parameter
