### ISSUE TITLE
Number total of element is incorrect when there is only one item

### ISSUE THREAD

**Issue by FroggDev** [filegator/filegator#30]
**Describe the bug**
when there is only 1 element number of total element is true instead of 1

**To Reproduce**
Given I installe the projet
When I uploaded my first file
Then i can see **Selected: 0 of true** instead of **Selected: 0 of 1**
And if I select the item i get **Selected: 1 of true** instead of **Selected: 1 of 1**

When If i upload another file
Then the total is correct
When I remove the 2nd file (to have only 1)
Then the bug still appear
When i remove all files
Then the total is correct
When I create a new folder
Then the bug still appear

So i can conclued bug exist when there is only 1 element.

**Expected behavior**
to have **Selected: ${x} of 1** when there is only one element

**Screenshots**
https://upload.frogg.fr/?r=/download&path=L2J1Zy5wbmc%3D

**Environment**
 - FileGator Version 7.14
 - Server: Apache 2.4 on Debian Linux
 - PHP Version 7.2
 - Browser Opera/Chrome/IE

**Additional context**
It seem to be a data type trouble 1 is sent as bool 1 = true instead of int 1 = 1
Can be seen there https://upload.frogg.fr/

**Comment by alcalbg** [comment]
Thanks for reporting this bug, I'll look into this

**Comment by alcalbg** [comment]
It seems the problem is with Lodash https://github.com/lodash/lodash/issues/2058

**Comment by alcalbg** [comment]
Should be ok now

**Comment by FroggDev** [comment]
Thanks really fast response and action !
