### ISSUE TITLE
Freature request: redirect on / instead of login page when logout

### ISSUE THREAD

**Issue by FroggDev** [filegator/filegator#31]
Is it possible to redirect on / instead of login page when you log out ?

- Case guest has no rights :
When you log out, the app will show the login page. (same as actual)

- Case guest has rights (read for example)
When you log out, the app show the folder content instead of the login page.

Thanks.

**Comment by alcalbg** [comment]
Thanks for your feedback. This will be included in the next release.

Cheers!

**Comment by FroggDev** [comment]
Thanks a lot !
