### ISSUE TITLE
Following symbolic links over SFTP

### ISSUE THREAD

**Issue by fbetil** [filegator/filegator#315]
Hello,
I use Filegator and connect to an SFTP server. Unfortunately, Filegator seems to not follow symbolic links. Instead, it try to download the File..
Thanks a lot

**To Reproduce**
Create a symbolic link in the home of the SFTP user (on redhat OS, sshd deamon).
Ensure tha SSHD is properly configured and user has proper rights to access to symbolic link's target
Configure Filegator to use this SFTP and user connection.
Click on the symbolic link in Filegator

**Expected behavior**
For example, with WinSCP, the user is redirected to the symbolic link's target

**Environment (please complete the following information):**
 - FileGator Version 7.7.1

**Comment by alcalbg** [comment]
Symlinks are not supported by the underlying Flysystem, see [limitations](https://github.com/filegator/filegator#limitations)
