### ISSUE TITLE
Downloading multiple files does not work

### ISSUE THREAD

**Issue by li-yang-wu** [filegator/filegator#316]
Downloading a single file works fine using the list button of the respective file entry.

When I select one or more files with the checkboxes, a download button appears above the file list. This button does not work, neither selecting a single file nor selecting multiple files.
What happens is that the following popup will show up.
![image](https://user-images.githubusercontent.com/75784791/160660482-639e967b-003e-4572-a0c6-eec429d7e133.png)
Clicking the download button in the popup does nothing. You can't click away the popup unless you reload the page.

**Comment by alcalbg** [comment]
Which browser are you using? Can you try another one?

**Comment by alcalbg** [comment]
Is there something in your logs? How about browser's console log?

**Comment by li-yang-wu** [comment]
Hi, the problem seems to be solved. Who ever fixed it, thank you.
