### ISSUE TITLE
Translate filegator to Arabic

### ISSUE THREAD

**Issue by MesterPerfect** [filegator/filegator#325]
hi
I translated filegator/tree/master/frontend/translations/english.js to Arabic
Can you add Arabic language file?
[arabic.js.txt](https://github.com/filegator/filegator/files/8778802/arabic.js.txt)

**Comment by alcalbg** [comment]
Thanks! added here https://github.com/filegator/filegator/commit/20cd7227f67378d8657baa8c94698c4833bbe2f3
