### ISSUE TITLE
Any plan to support symlinks (knowing the current limitation)

### ISSUE THREAD

**Issue by BancarelValentin** [filegator/filegator#329]
First I'm sorry as I know a lot of people are asking for that. I did read all (I believe) the issues mentioning the subject and I understand that because you use flysystem symlinks can't work as of now.

I also checked their issue tracker and it is not a bug but an actual feature by their principles.

In the readme you mention that limitation but you don't give info on weither or not you may want to change take necesasry actions to make it work. I know changing the underlaying system is certainly much work but you have made the greatest http file server, I couldn't find any other a tenth as good (and I looked into 20 others I believe).

I just wanna know if I can have some hope to see symlinks working one day or just have to implement my thing myself.

Thanks for all the good work tho ! <3

**Comment by alcalbg** [comment]
Thanks for your support!

I have no plans for making symlinks work.

**Comment by alcalbg** [comment]
You can use SKIP_LINKS flag to ignore symlinks and bypass errors. 

Adjust your configuration.php file:
```
        'Filegator\Services\Storage\Filesystem' => [
            'handler' => '\Filegator\Services\Storage\Filesystem',
            'config' => [
                'separator' => '/',
                'config' => [],
                'adapter' => function () {
                    return new \League\Flysystem\Adapter\Local(
                        __DIR__.'/repository',
                        LOCK_EX,
                        \League\Flysystem\Adapter\Local::SKIP_LINKS,
                    );
                },
            ],
        ],
```
