### ISSUE TITLE
Zip file is invalid

### ISSUE THREAD

**Issue by brjdk** [filegator/filegator#339]
**Describe the bug**
I get an error saying "the zip file is invalid", when trying to download from the test installation on my domaine.

**To Reproduce**
Downloaded filegator from https://filegator.io/ 
Installed on local server using '
- xampp
- php version 8.1.6
- zip version 1.19.5
and the zip-file works fine. 

I then upload to my domain 
- php 8.0.21
- zip version 1.19.5
then I get the error "zip file is invalid". 

**Expected behavior**
Working zip file. 
There is no problem when using the demo on https://demo.filegator.io/#/

**Environment (please complete the following information):**
 - FileGator Version latest
 - Browser chrome

Please let my know if you need any more information.

**Comment by brjdk** [comment]
Now this is really stange - if I upload a png file either via ftp or filegator, its broken when I try to download it via filegater, both if I  press the file, or select to download zip file. 

![20](https://user-images.githubusercontent.com/14264070/180390000-8d2cde8b-1d19-48b8-ae09-597d1547d4c3.jpg)
![test](https://user-images.githubusercontent.com/14264070/180390108-3dbc701e-e423-4085-bf21-300dbeef3409.JPG)

**Comment by brjdk** [comment]
Sorry for writing all these posts..... 
I just checked the app.log logfile in /private/logs, and there seems to bee an error on line 61 in the file DownloadController.php. 

[2022-07-22 07:41:58] default.NOTICE: E_NOTICE: ob_flush() [<a href='http://php.net/manual/en/ref.outcontrol'>ref.outcontrol</a>]: failed to flush buffer. No buffer to flush {"code":8,"message":"ob_flush() [<a href='http://php.net/manual/en/ref.outcontrol'>ref.outcontrol</a>]: failed to flush buffer. No buffer to flush","file":"/var/www/xxx/public_html/backend/Controllers/DownloadController.php","line":61} []

I might install filegator in a wrong way? I have just copied the files and folders to the /public_html/, but I can see that I should 
"Set the website document root to filegator/dist/ directory. This is also known as 'public' folder". 
Can that course the problem and if so, how do I fix it? :-)  

Sorry for all my questions - I hope to get FileGater up and running soon :-)

**Comment by alcalbg** [comment]
Hi,

Thank you for reporting this.

Can you try with the latest version? I've just released v7.8.2 with a fix for this included.

https://github.com/filegator/static/raw/master/builds/filegator_latest.zip

Let me know if you see any errors afterwards

**Comment by brjdk** [comment]
Thanks Milos 
It works just fine now :-)

Regarding installation, do I do it when when I just copy the installation to /public_html? 
A huge thank you for helping me out.

**Comment by alcalbg** [comment]
You should follow the docs https://docs.filegator.io/install.html or consult with your hosting provider
