### ISSUE TITLE
change date format

### ISSUE THREAD

**Issue by lancod** [filegator/filegator#34]
Hi, 
is it possible to change the date format to "dd.mm.yyyy" and the time format to 24h ?
It currently looks like this: "yy/mm/dd/" and "pm/am:mm:ss"

currently looks:
![grafik](https://user-images.githubusercontent.com/59925007/72520118-08da7200-3859-11ea-9163-bf55e91a07db.png)

thank you, best regards

**Comment by alcalbg** [comment]
Yes, see here: https://github.com/filegator/filegator/blob/master/frontend/mixins/shared.js#L65

**Comment by alcalbg** [comment]
Actually, this should be a config variable, so, I'll tag this as a feature request.

Thanks

**Comment by lancod** [comment]
Perfect, thank you.

**Comment by alcalbg** [comment]
Added as config variable in v7.2.1
