### ISSUE TITLE
Wrong homedir and security issue 

### ISSUE THREAD

**Issue by jbarmanet** [filegator/filegator#349]
Hi Folks, thank you for this great job. 
I found an issue and fixed it into a fork. Here is the bug:

**Describe the bug**
When Administrators are created within a subdirectory, the users they will create will get either a wrong path as homedir and won't see any file, or worse they could get access to the repository root and see everything. 

**To Reproduce**
1. As super admin, create this tree: Home > Directory_A > Directory_B > Directory_C
2. Create an Administrator user called UserAdmin and set `Directory_B` for his home dir
3. Signin as UserAdmin and put a file into `Directory_C` 
4. Still as UserAdmin create a new user Visitor1 and give him `Directory_C` as home dir
5. Create also a second new user Visitor2 and for his homedir click on the very first tree node called `Home`
6. First issue: Signin as Visitor1, you won't see the file you put in `Directory_C` at step 3
7. Second issue: Signin as Visitor2, you can access _everything_ from root repository

**Expected behavior**
If a subdirectory Admin was created within a subdirectory, the same home subdirectory setting should apply to every new user he creates.

**Fix**
The fork: https://github.com/jbarmanet/filegator/tree/Fix-Root-Directory-Permissions-

The way I fixed the issue: as the Tree selector Vue component doesn't consider if the current logged user is already into a homedir, so the fix is to reinject the current admin homedir in the UserEdit form field when a node is selected, so the new user path is never wrong. 
The only downside of this fix is that it discloses the full path to the admin, I think a better fix would not handle this from frontend, but  reinject the right path from the backend, when writing the json file…

**Comment by alcalbg** [comment]
Hi,

Thank you for your elaborate report. I fixed the issue on the backend as you suggested.

Can you please try it out and confirm the fix?

https://github.com/filegator/filegator/commit/24119f7cf4f8d813f7e9b07fae9fd3c82c5e66cd
