### ISSUE TITLE
additional simple login security

### ISSUE THREAD

**Issue by lancod** [filegator/filegator#35]
Hello,

is it possible to block an IP for e.g. 1 hour after 3 unsuccessful logins? And after another 2 unsuccessful logins, to ban them forever? And with a corresponding note. (without cookies)

Is there anything like that? If so, how can I implement it?
If not, is there another login security solution? ( I don't like google-recaptcha!!! )

Note: I use the precompiled build

thank you

**Comment by alcalbg** [comment]
You can build a new custom Auth adapter or modify existing one and add those features, see this for more info: https://docs.filegator.io/configuration/auth.html
