### ISSUE TITLE
Repository Name or User Name visibility before Profile Filed      

### ISSUE THREAD

**Issue by b4allb4u** [filegator/filegator#36]
Hello Dev Team! 

I really appreciate your hard work! is it possible to add the Repository name or user name visibility before the Profile Filed after successful login the user?

**Comment by jannyba** [comment]
+1 for showing Username on the main page after login

**Comment by alcalbg** [comment]
added in 3e0b34d37a9847f82c5a46b106d61cf3ccddada7

**Comment by b4allb4u** [comment]
**_Hi@alcalbg_**

I have updated my Filegator to the latest stable version of V 7.3.0. But the system not shown the username after user login. Pls, help me.......

thanks in adv.

**Comment by alcalbg** [comment]
You must wait for the next release (probably 7.3.1) or use the current master branch via git

**Comment by b4allb4u** [comment]
Hi @alcalbg Excellent and thanks a lot for the latest version of **V7.3.1**. If possible, Pls add a password visibly/ hide option on the user login page. this will help the user to verify his/her password before clicking on the Login button and this will avoid the multiple wrong entries on the user password field.

**Comment by alcalbg** [comment]
Added, cheers!
