### ISSUE TITLE
Error uploading files

### ISSUE THREAD

**Issue by JoanLlu** [filegator/filegator#366]
Suddenly files can't be uploaded.
Logs show this error:

 Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function isValid() on array in /var/www/filegator/backend/Controllers/UploadController.php:70\nStack trace:\n#0 [internal function]: Filegator\\Controllers\\UploadController->upload(Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response))\n#1 /var/www/filegator/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array)\n#2 /var/www/filegator/vendor/php-di/php-di/src/Container.php(269): Invoker\\Invoker->call(Array, Array)\n#3 /var/www/filegator/backend/Services/Router/Router.php(78): DI\\Container->call(Array, Array)\n#4 /var/www/filegator/backend/App.php(33): Filegator\\Services\\Router\\Router->init(Array)\n#5 /var/www/filegator/dist/index.php(53): Filegator\\App->__construct(Object(Filegator\\Config\\Config), Object(Filegator\\Kernel\\Request), Object(Filegator\\Kernel\\Response), Object(Filegator\\Kernel\\StreamedResponse), Object(Filegator\\Container\\Container))\n#6 {main}\n  thrown in /var/www/filegator/backend/Controllers/...'

We're using php-fpm-8.1.13-1.fc37.x86_64 package with Filegator 7.4.5.

Any help? 
Thank you so much.

**Comment by alcalbg** [comment]
Hi,

This has been [reported](https://github.com/filegator/filegator/issues/295) and fixed [here](https://github.com/filegator/filegator/commit/c158aa37aa7a0bc2eba2c4da471ad23624484ee4) .

Please update / use the latest filegator version.

Cheers
