### ISSUE TITLE
Simpified Chinese Translation Finished

### ISSUE THREAD

**Issue by zbx1425** [filegator/filegator#37]
Hi dev!
Just translated this project into Simpified Chinese.
Unfortunately, I currently do not have a Vue compile kit at my computer, so I chose the uglier way to present it to you.
[chinesesimpified.zip](https://github.com/filegator/filegator/files/4169129/chinesesimpified.zip)
Thanks for this awesome project!

**Comment by alcalbg** [comment]
Thank you very much for this. Your translation is included.

Cheers!
