### ISSUE TITLE
Timeout for incorrect login attempts?

### ISSUE THREAD

**Issue by vishnu350** [filegator/filegator#374]
Is there are way to enable incorrect login attempt timeouts? As of the latest version, it seems there is no way to do this. Users are allowed infinite login attempts when inputting wrong usernames/passwords.

A login timeout should be enforced to cripple bruteforcing scripts.

**Comment by alcalbg** [comment]
Hi,

Thanks for your suggestion. This option was just added to v7.9.0. You can update and try it out.

See how lockout options are used in configuration.php here: https://github.com/filegator/filegator/blob/master/configuration_sample.php

**Comment by vishnu350** [comment]
That was fast! Was going through the source to implement a half baked pull request. Timeout works now, security probably just went up tenfold vs script kiddies (on the rise as of late). Nice work.

**Comment by alcalbg** [comment]
Ah, there was a bug in this, you should update to 7.9.1

**Comment by vishnu350** [comment]
Thank you. Tested it, works well on my end.
