### ISSUE TITLE
Running FileGator on Port 80 with Docker User (www-data)

### ISSUE THREAD

**Issue by bjo004** [filegator/filegator#376]
**Describe the bug**
If you run filegator using the Dockerfile provided using port 80 and with docker user www-data you will get a permission denied. 
I'm running filegator in a kuberntes cluster. 

**To Reproduce**
1. Run filegator in kubernetes and on starting up it will immediately crash.
2. Looking at the error, it says the following
3.  AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.16.29.2. Set the 'ServerName' directive globally to suppress this message
4. (13)Permission denied: AH00072: make_sock: could not bind to address :80
5.  (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80 
6.  no listening sockets available, shutting down
7. AH00015: Unable to open logs

**Expected behavior**
It's supposed to run and I'm supposed to access it via port 80

**Screenshots**
![image](https://user-images.githubusercontent.com/5459828/214547399-49d15ffc-15eb-4ded-9015-8c81372a8e72.png)

**Logs**
If applicable, add relevant FileGator logs entries from ```/private/logs/app.log``` or web server logs.

**Environment (please complete the following information):**
 - FileGator Version [e.g. 7.9.1]
 - Server: [e.g. Kubernetes Cluster 1.23.12]
 - PHP Version [e.g. PHP 7.3]

**Additional context**
I believe removing the USER field in the Dockerfile and allowing the process run as root will fix the issue or if you still want to run as user (www-data) change the port to a number greater than 80 (e.g. 8080)

**Comment by bjo004** [comment]
In your Dockerfile, you can add more sed commands to change the default port from 80 to another port (e.g. 8080)
`
ENV APACHE_PORT=8080

RUN  sed -ri -e 's!80!${APACHE_PORT}!g' /etc/apache2/ports.conf && \
         sed -ri -e 's!:80!:${APACHE_PORT}!g' /etc/apache2/sites-available/000-default.conf && \
         sed -ri -e 's!:80!:${APACHE_PORT}!g' /etc/apache2/sites-enabled/000-default.conf && \
`
Kind regards,

Bankole.

**Comment by alcalbg** [comment]
Hi,

Thanks for reporting the issue and providing a possible solution.

This is probably related to [this issue](https://github.com/moby/moby/issues/8460) and it would also potentialy solve [this](https://github.com/filegator/filegator/issues/206).

**Comment by alcalbg** [comment]
Which docker version are you using?

Mine is Docker 20.10.22 (Debian 11) and it works with port 80 and non-root user (www-data).

**Comment by alcalbg** [comment]
Everything should be updated now, can you try it out? The new internal port is 8080

**Comment by bjo004** [comment]
I've seen your changes. Will you also change the default ports in the `sites-enabled` location? 

`sed -ri -e 's!:80!:${APACHE_PORT}!g' /etc/apache2/sites-enabled/000-default.conf `

Kind regards,

Bankole.

**Comment by alcalbg** [comment]
Well, the "sites-enabled" is just a symlink to the "sites-available", no need to update both

```
lrwxrwxrwx 1 root root   35 Nov 15 04:30 000-default.conf -> ../sites-available/000-default.conf
```

https://github.com/filegator/filegator/blob/28953bb83cf2ce5efd6319d5c60048d465440116/Dockerfile#L53

**Comment by bjo004** [comment]
I'm running this and it's working as expected. Great work man and thank you for building this.

**Comment by alcalbg** [comment]
Great! Thanks again for your help pinpointing the issue!
