### ISSUE TITLE
Remove Navbar | Logo etc.

### ISSUE THREAD

**Issue by treybowman** [filegator/filegator#378]
Is there a way to hide the nav bar? Logo login and all? I am trying to use this on a WordPress site with a public folder only guests would use.

Thank you!

**Comment by alcalbg** [comment]
Hi,

You can use "add_to_head" to add some css and hide stuff that you don't use (display:none)

https://docs.filegator.io/configuration/basic.html

**Comment by alcalbg** [comment]
See https://github.com/filegator/filegator/issues/85
