### ISSUE TITLE
Slow Search

### ISSUE THREAD

**Issue by uandiweb** [filegator/filegator#379]
**Describe the bug**
I use FileGator to host about 30,000 files. When I search for files it can take as much as 1 minute to find it. Is there are a way to improve it? Thank you

**To Reproduce**
1. Upload thousands of files
2. Search for files

**Expected behavior**
Files will get found within seconds, but it can take much longer

**Environment (please complete the following information):**
 - FileGator Version: Latest
 - Server: Apache 2.4
 - PHP Version: 8.1
 - Browser: Chrome

**Comment by alcalbg** [comment]
Hi,

That seems like a lot of files. Maybe this app isn't the right tool for your use-case.

**Comment by uandiweb** [comment]
@alcalbg 

Actually this software is excellent, and can mange 30,000 easily. The only drawback is the search speed. If this will be improved (and I'm sure it can be improved) - the wait time for results can be decrease from about 1 minute to a few seconds.

Thank you

**Comment by uandiweb** [comment]
Good news: I notices in the configuration file the option to adjust the search speed. I increased 'search_simultaneous' => 5 to 500, and now the search works fast. Even with 30,000+ files.
