### ISSUE TITLE
public_html as home folder

### ISSUE THREAD

**Issue by junglized** [filegator/filegator#38]
Hello,

I was using older versions of Filegator, where it was possible to set home folder out of filegator's own folder, and that was relatively easy to do, just by fiddling with configuration file. Unfortunately I can't see this option in current version of Filegator. I installed Filegator in `public_html/filegator`. Filegator's home folder is set for `html_public/filegator/repository`. Is it possible to set home folder as public_html?

Thanks and best regards!

**Comment by alcalbg** [comment]
Hi,

You can still use any absolute path in your configuration.php file:

```
        'Filegator\Services\Storage\Filesystem' => [
            'handler' => '\Filegator\Services\Storage\Filesystem',
            'config' => [
                'separator' => '/',
                'config' => [],
                'adapter' => function () {
                  return new \League\Flysystem\Adapter\Local(
                      '/my/full/path/on/disk'
                      );
                },
            ],
        ],
```

**Comment by junglized** [comment]
I used `getcwd() . '/..'` instead of full path and that worked as well. The only problem was I couldn't find the appropriate option.

Thank you very much for your time and help.
