### ISSUE TITLE
Account Lockup

### ISSUE THREAD

**Issue by uandiweb** [filegator/filegator#380]
**Describe the bug**
Currently there is no block on the number of failed login attempt. In other words, a bot can try unlimited possibilities till it's able to login without authorization.

**To Reproduce**
Attempt multiple login with wrong credentials

**Expected behavior**
After X (10?) number of failed logins, there will be a temporary block on the IP attempting to login.

**Comment by alcalbg** [comment]
The latest version includes this feature, please upgrade to 7.9.2
