### ISSUE TITLE
Using Symlinks

### ISSUE THREAD

**Issue by aziegler3** [filegator/filegator#39]
We have just updated to the most recent version of FileGator on a Windows 2012 R2 server running Apache.

There was a documented workaround for getting a previous version of FileGator to navigate symLink directories. We would like to be able to do this again in the new version in order to support common user directories.

Thank you

**Comment by alcalbg** [comment]
Unfortunately, symlinks are not supported by underlying Flysystem adapters https://github.com/thephpleague/flysystem/issues/599
