### ISSUE TITLE
How to remove header

### ISSUE THREAD

**Issue by mvldebian** [filegator/filegator#395]
I'm integrating the filegator to a wordpress project, I need to remove the header where it shows the username and the exit button, but I couldn't find which file it is in.

Can you help?

![image](https://user-images.githubusercontent.com/25337130/235642820-c8a17192-a9a4-471f-af16-30d3fdf9331e.png)

**Comment by alcalbg** [comment]
See https://github.com/filegator/filegator/issues/378 and https://github.com/filegator/filegator/issues/85
