### ISSUE TITLE
Fix Development Mode

### ISSUE THREAD

**Issue by treehstn** [filegator/filegator#416]
Looks like I screwed up the install and installed filegator at the root if I'm getting this message when using the program?  How can I fix it?  Do I have to completely uninstall and then reinstall?  I'm assuming that will delete all the files I already have uploaded?

TY!

**Comment by alcalbg** [comment]
You can either change your web root to filegator/dist/ or move the filegator folder around. No need to reinstall if you know what you are doing, but make a backup just in case.

**Comment by treehstn** [comment]
This is a site that I have coppermine gallery as the main site of the domain.  also have wordpress just to host a links library.  then have filegator.  where would I be moving filegator to?

**Comment by alcalbg** [comment]
Ideally, into separate subdomain with its own web root configuration.
