### ISSUE TITLE
can't run unless the repository is writable

### ISSUE THREAD

**Issue by JohnOstrowick** [filegator/filegator#423]
Bug: filegator can't run unless the repository is writable

Comment: this should not  be necessary if the repository is intended as read-only for downloads only

Risk: making it rwx-rwx-rwx opens it up for attacks e.g. wordpress vulnerability attacks, which I get quite a lot of.

Workaround: none

Proposal: make it a config option to have a read-only repo, and if writable is needed, provide a tmp/ directory to write temp files into, e.g.  if you need to zip things.

**Comment by alcalbg** [comment]
Hi,

What do you mean by can't run? Do you get an error or something?

The actual demo is read-only https://demo.filegator.io and you can see how it is configured in Dockerfile: https://github.com/filegator/demo

**Comment by JohnOstrowick** [comment]
hi. Meaning it stops and returns an error saying "repository is unwritable" and goes no further.

Dr John Ostrowick
HdipEd MA PhD
Cell - 082-979-6812
Web - www.ostrowick.co.za

**Comment by alcalbg** [comment]
Oh yes, I see it now.

It is hard-coded to check for ../repository folder but I've replaced that in configuration file with /var/www/demorepo/ and that's why it works for me.

Do, yes, this check should be removed I guess.

**Comment by alcalbg** [comment]
You can try with the latest version released just now.

**Comment by JohnOstrowick** [comment]
Thank you

**Comment by JohnOstrowick** [comment]
Hi there. Thanks for this fix. I see it still has the same complaint for private/logs. On my site I can't have anything writable because I get wordpress attacks dumped into anything writable. Can you put a config flag to say "log errors" or somesuch and if the flag is set to false, tell it to not look for a writable logdir or to write to apache's normal log file? Thanks
