### ISSUE TITLE
More settings from configuration.php via web page for admin

### ISSUE THREAD

**Issue by jannyba** [filegator/filegator#44]
Hello,

would be nice, if more settings from configuration.php will be available for admins via web site.
For example:
- language
- date format
- logo
- app name
- max upload size, chunk size, default archive name, editable files, basically all from the configuration.php

thank you all for your time!

**Comment by alcalbg** [comment]
Thanks for your suggestion. However, I think this could introduce more complexity than usability so I I will close the issue, at least for now.

Cheers!
