### ISSUE TITLE
"Copy link" doesn't work

### ISSUE THREAD

**Issue by jannyba** [filegator/filegator#47]
Hi

how exactly should work Copy link function? When I'm logged, copy link of a file and open it in anonymous window I see only text "Not Found", there is nothing in the app.log.

When I copy link in the window where I'm logged in, it only refresh page in folder where I was (not in the folder with the linked file).

thx

**Comment by alcalbg** [comment]
This was broken, let try it out on the next release.

**Comment by jannyba** [comment]
Hello,

also can be the random string a tiny bit longer? or it is proof against brute force attacks?
also have the download links some timeout or they are permanent?

thank you

**Comment by alcalbg** [comment]
Random string in the link is just a base64-encoded file path. Link is permanent, unless you move or rename the file itself.

https://github.com/filegator/filegator/blob/fd2d3d2f92871aaad7b254dcd5fbfef741a7bcea/frontend/mixins/shared.js#L124
