### ISSUE TITLE
Bug report - npm install crashed

### ISSUE THREAD

**Issue by Norr** [filegator/filegator#501]
**Describe the bug**
Following the development instruction, the `npm install` failed. Error log below.

[2024-11-20T11_43_10_944Z-debug-0.log](https://github.com/user-attachments/files/17830171/2024-11-20T11_43_10_944Z-debug-0.log)

**Comment by alcalbg** [comment]
Try with node 14

**Comment by kobizz** [comment]
Hi @Norr, @alcalbg,

You can seamlessly run it on node 20 and probably newer, with only replacing `node-sass` package with `sass` package inside `package.json`.

It will work out of the box and will fix some vulnerability issues on the way.

**Comment by Norr** [comment]
@kobizz , @alcalbg  sorry guys but the code (backend and fronted) has to many vulnerabilities, I can't use this soft for now.
