### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by harro1968** [filegator/filegator#55]
Have installed FileGator - struggling with findinig documentation for configuration.

Essentially I'd like the home directory for browsing to point to /Files on my server - can't seem to find a way to do that?

Thanks

David

**Comment by alcalbg** [comment]
Hi,

You should check the storage documentation here: https://docs.filegator.io/configuration/storage.html

Basically, in your configuration.php file, replace the storage service config (lines 76-87) with something like this:

```
        'Filegator\Services\Storage\Filesystem' => [
            'handler' => '\Filegator\Services\Storage\Filesystem',
            'config' => [
                'separator' => '/',
                'config' => [],
                'adapter' => function () {
                  return new \League\Flysystem\Adapter\Local(
                      '/Files'
                      );
                },
            ],
        ],
```

You also need to make sure your web server can read/write to this ```/Files``` folder.
