### ISSUE TITLE
Archiver Service throwing an error

### ISSUE THREAD

**Issue by 44db** [filegator/filegator#58]
Hello,

This is for Filegator v 7.3.4

Here's my environment:

- Centos 7.7.1908
- nginx 1.16.1
- php 7.3.16

When using the zip feature it throws an error:
POST request ?r=/zipitems throws a 500 error

Javascript Console
File: **vue-router.esm.js:2051**
```
Uncaught (in promise) 
name: "NavigationDuplicated"
message: "Navigating to current location ("/") is not allowed"
```
any help on setting this up

All other feauters (create/delete/edit/move file(s), download, upload etc) work as expected.

Thanks

**Comment by alcalbg** [comment]
Hi,

You should look what went wrong in filegator/private/logs/app.log file. You will probably see something like this `Uncaught Error: Class 'ZipArchive' not found`

If this is the case, then you don't have php zip module installed or enabled. For debian based linux you can get this with `apt install php-zip` but I'm not sure for centos, probably something like `yum  install php-pecl-zip`

Let me know if this helps.

Milos

**Comment by 44db** [comment]
Hi Milos and thanks for the prompt reply,
That did it! Thank you very much.
Yannis
