### ISSUE TITLE
access multi dir for user

### ISSUE THREAD

**Issue by xMedoo** [filegator/filegator#59]
i can only give user access for one dir,
and i couldn't give him permission for multi dir

**Comment by alcalbg** [comment]
Yes, this is the app limitation. You can only mount a single home folder with a single set of permissions per user.

**Comment by iManchaDev** [comment]
Typical use cases
--
63 | - share a folder with colleagues, your team, friends or family

As per the read me - How do you go about sharing a folder with another user?

**Comment by alcalbg** [comment]
If John, Jane, and Peter have the same home folder configuration then they all see the same files. Permissions can be different so that, for example, only Peter can write or upload.

**Comment by iManchaDev** [comment]
Thanks, how or where are permissions set?

I'm using WordPress for authentication, would this override user permissions.

**Comment by alcalbg** [comment]
For WordPress auth adapter, permissions are set in the config file, they are same for all users, see [docs](https://docs.filegator.io/configuration/auth.html#configuring-auth-service-to-use-wordpress)
