### ISSUE TITLE
Fix docs

### ISSUE THREAD

**Issue by robertsLando** [filegator/filegator#60]
Dev docs actually are:

```
git clone git@github.com:filegator/filegator.git
cd filegator
cp configuration_sample.php configuration.php
sudo chmod -R 777 private/
sudo chmod -R 777 repository/
composer install
npm install
npm run build
```

Fixed: 

```
git clone https://github.com/filegator/filegator.git
cd filegator
cp configuration_sample.php configuration.php
sudo chmod -R 777 private/
sudo chmod -R 777 repository/
apt install composer
composer install
npm install --unsafe-perm
npm run build
```

Fixed link using https, install composer missing apt, add `--unsafe-perm` to fix install issue with  `cypress`

**Comment by Andrefly** [comment]
Hi, 
when I send composer install appare this:
Your requirements could not be resolved to an installable set of packages
How can I fix?
Thank you!

**Comment by robertsLando** [comment]
@Andrefly  https://stackoverflow.com/questions/29318709/how-can-i-resolve-your-requirements-could-not-be-resolved-to-an-installable-set

**Comment by Andrefly** [comment]
Thank you!

**Comment by janstieler** [comment]
Hi,
the typos are existing on the readme.md (https://github.com/filegator/filegator#project-setup-for-development-linux).
Could you fix it here?
