### ISSUE TITLE
user accounts: disable password changing

### ISSUE THREAD

**Issue by robert-andreas** [filegator/filegator#66]
Hey there :-)

First of all, thank you very much for FileGator :-D

I wanted to ask if it's possible to disable password changing for users ... or everyone ;-)

Regards,
Robert

**Comment by alcalbg** [comment]
Hi,

No, this feature is not available but it's a nice suggeation for some future update.

Thanks

**Comment by alcalbg** [comment]
Maybe you could add some style/css to the head to hide this? https://docs.filegator.io/configuration/basic.html

**Comment by alcalbg** [comment]
With the latest version (v7.4.0+) you can configure your `ViewInterface` in `configuration.php` and hide this option from the menu like this:

```
'add_to_head' => '<style>.navbar-item.profile{display:none!important}</style>',
```

**Comment by nubblesite** [comment]
> With the latest version (v7.4.0+) you can configure your `ViewInterface` in `configuration.php` and hide this option from the menu like this:
> 
> ```
> 'add_to_head' => '<style>.navbar-item.profile{display:none!important}</style>',
> ```

Does not seem to work in 2023

**Comment by ralhako** [comment]
'add_to_head' => in configuration.php do not work!

put .navbar-item.profile{display:none!important} in new line at end of filegator/dist/css/app.css works!!
