### ISSUE TITLE
Cannot apply indonesian lang

### ISSUE THREAD

**Issue by devteam21** [filegator/filegator#7]
I've translate this project to Indonesian, and pull with ur help .. and trying to apply today, but as u see in here (Screenshoot)

#TR unknow error and all of variable string is TR

![Capture](https://user-images.githubusercontent.com/19890311/62847864-d1dcbf00-bd02-11e9-9739-fb780814e285.PNG)

**Comment by alcalbg** [comment]
Please check your configuration.php file, it should look like this:

``` 'language' => 'indonesian',```

Note the 'n' at the end.

For the reference `TR:` means Translation Required.

**Comment by devteam21** [comment]
Sure, i know that but .. Im trying to change another lang "spanish" "german" and worked 100% but "indonesian" still error TR
![1](https://user-images.githubusercontent.com/19890311/62853064-6cde9480-bd15-11e9-83c3-62a711414fe8.PNG)

for make sure, i change to german is worked ..
![2](https://user-images.githubusercontent.com/19890311/62853231-dced1a80-bd15-11e9-89f1-795077f5c6e2.PNG)

**Comment by alcalbg** [comment]
I've tried with fresh `git clone git@github.com:filegator/filegator.git` and it works fine. Did you use git clone or you just downloaded compiled version?

**Comment by devteam21** [comment]
Sorry for late respone, all picture at above I've downloaded directly from https://github.com/filegator/static/raw/master/builds/filegator_v7.0.1.zip

and im trying clone using git bash and honestly im not understand lol which file should I take and put it on my server .. ??
![image](https://user-images.githubusercontent.com/19890311/63167993-1945b100-c05d-11e9-8785-c7d631734726.png)

#note, the person who settings all of indonesian translations is you like in the below of the picture, it should have worked, and i just need to change the configuration file to "indonesian" .. 
![image](https://user-images.githubusercontent.com/19890311/63168174-9cff9d80-c05d-11e9-8b4c-2ccb4e08504f.png)

Sorry for rip english or bothering you, I intend to help this project and study ..

**Comment by alcalbg** [comment]
Please try again with the latest version. Clean install.

**Comment by alcalbg** [comment]
No response, closing this...
