### ISSUE TITLE
Auto Login 

### ISSUE THREAD

**Issue by prionkor** [filegator/filegator#72]
First of all thank you for the amazing repository. Looks fabulous.

I am looking to use this file manager as a part of another application. I would like to authenticate user to use the file manager when user is authenticated on the parent application.

So, what I am looking for is similar: 

```
if( is_logged_in_parent() ){
    $auth->authenticate();
}else{
   $auth->forget();
}
```

Will it need a new type of adapter?

**Comment by alcalbg** [comment]
Hi,

Yes, you need a new Auth adapter for your application that matches the [AuthInterface](https://github.com/filegator/filegator/blob/master/backend/Services/Auth/AuthInterface.php).

Basically, this adapter will try to authenticate the user in your application and store a [User](https://github.com/filegator/filegator/blob/master/backend/Services/Auth/User.php) object into the application session.

Two different adapters are already provided so you can start by looking at these two - [database](https://github.com/filegator/filegator/blob/master/backend/Services/Auth/Adapters/Database.php) and [json](https://github.com/filegator/filegator/blob/master/backend/Services/Auth/Adapters/JsonFile.php).

You also need to add this new adapter to your ```configuration.php``` file as ```Filegator\Services\Auth\AuthInterface``` handler.

Hope this helps,

Cheers

**Comment by alcalbg** [comment]
Look at this simplest demo auth adapter: https://github.com/filegator/demo_auth_adapter

**Comment by prionkor** [comment]
Thank for your support. I have started working on it. I will post update with code sample here if I can implement it. :)

Closing this issue for now.

**Comment by avinashpatwari** [comment]
@prionkor Have you implemented code to create user session in filegator once user loggeIn to wordpress site?

@alcalbg  What I am implementing is to set user session from external file/plugin. Current Auth adaptor seems create login session once user login to filegator system, I am looking for reverse login.
