### ISSUE TITLE
A way to hide certain file types and specific folders?

### ISSUE THREAD

**Issue by SirCheese87** [filegator/filegator#76]
So I'm using Windows IIS 10 to host FileGator (I can hear the boos now) and I have FileGator pointed to a separate hard drive full of files and folders.

What I'd like to do is hide the file type ".DS_Store" that Mac computers always leave behind and to file the "Recycle.bin" folder and "File System Information" folder that is present on all Windows NTFS drives in the root. I know I can just put all my stuff inside another folder, and not the root, to hide those system folders but I don't want to do that. More importantly is the hiding of the files that are normally hidden in Windows (such as .ds_store).

Any way to do this?

**Comment by alcalbg** [comment]
There is no such feature at the moment but I like the idea. Tagging this as a feature request.

Good to know it works on Windows.

**Comment by SirCheese87** [comment]
It works on IIS, but it would ignore all the htaccess files because IIS uses web.config files.

Also: When accesses through a phone, the interface is a mess.
