### ISSUE TITLE
Who is using FileGator?

### ISSUE THREAD

**Issue by alcalbg** [filegator/filegator#77]
Drop your company name, SVG logo, and a link to your website. I'm looking to add these to the official website.

**Comment by squeaksci** [comment]
I assume it's not worth linking, but I still want to mention, I'm using FileGator at home for friends and family. It seems to be working well, thank you!

**Comment by mckaygerhard** [comment]
hi  @alcalbg  i like and will paste your logo in our two companies! but i need also older version .. you mention that version 7 was written from stract.. so olders version (dont worry about security.. ) for sure are php5 so.. where are those versions?

**Comment by alcalbg** [comment]
The [older version](https://codecanyon.net/item/filegator/3041013) was released under a different license. It is not available anymore.

**Comment by mckaygerhard** [comment]
@alcalbg  :facepalm:  you deleted XD the item.. ? i dont care the license.. i only wnats the files! where are the files?

**Comment by mckaygerhard** [comment]
@alcalbg  :facepalm:  you deleted XD the item.. ? i dont care the license.. i only wnats the files! where are the files? what happend? if are older dont care the usage right!?

**Comment by Torsten-K** [comment]
> @alcalbg  you deleted XD the item.. ? i dont care the license.. i only wnats the files! where are the files? what happend? if are older dont care the usage right!?

The old versions were under a proprietary license, and you had to pay a license fee. I think those old versions wouldn’t run under PHP 7.4 or 8, and they were not as secure as the recent versions.

**Comment by mckaygerhard** [comment]
ok dont care abou7t it.. i need the older ones.. my question is about olders versions.. not newers one.. security and related issues is my bussines.. so can you answered the question?

> > @alcalbg  you deleted XD the item.. ? i dont care the license.. i only wnats the files! where are the files? what happend? if are older dont care the usage right!?
> 
> The old versions were under a proprietary license, and you had to pay a license fee. I think those old versions wouldn’t run under PHP 7.4 or 8, and they were not as secure as the recent versions.

what part you dont understand that i dont care that stupid of security etc etc, i will pay license, i do not use that php 7 stupid version.. where are those older ones?

why all the people always excuse with the fashioned way of security

**Comment by Torsten-K** [comment]
> what part you dont understand that i dont care that stupid of security etc etc, i will pay license,

The old versions are no longer available, what’s so difficult about it to understand? Follow the link that @alcalbg gave you and read the text: _Item no longer available_. Period.
