### ISSUE TITLE
request: User Register

### ISSUE THREAD

**Issue by vagra** [filegator/filegator#79]
this filegator is very good!

I was find & try 10+ web file manager at github, filegator is the most suitable for me.

the JQuery File Upload very good, but it can't make folder.

I'll using filegator for multiple user, so I want the user register feature, every user use a folder named with his username.

**Comment by alcalbg** [comment]
You can switch the auth adapter to use database as described here https://docs.filegator.io/configuration/auth.html

Once you have your users in mysql, it becomes trivial to build a simple form/script and add or register more users. Anyone here interested in building this?

**Comment by vagra** [comment]
thanks. I'll try it.
