### ISSUE TITLE
Feature Request : Overwrite Files

### ISSUE THREAD

**Issue by Gorescore** [filegator/filegator#8]
Is it possible to overwrite Files with the same name ?

**Comment by Gorescore** [comment]
And maybe with an E-mail notification when file is changed ?

**Comment by Gorescore** [comment]
Only on upload.

For the other cases the rename function is more than enough.

Thank you.

**Comment by github-canni** [comment]
Commenting out lines 168 - 170 in _\backend\Services\Storage\Filesystem.php_ worked for me:

`/*while ($this->storage->has($destination)) { $destination = $this->upcountName($destination); }*/`

**Comment by Gorescore** [comment]
Perfect, worked.
Thank you !

**Comment by alcalbg** [comment]
Properly fixed with a new config variable
https://github.com/filegator/filegator/releases/tag/v7.3.4
