### ISSUE TITLE
Is the sorting arrow direction correct?

### ISSUE THREAD

**Issue by jannyba** [filegator/filegator#82]
Hello!

Just want to bring to your attention small thing - orientation of the arrow showing us the sorting for:
- filenames
- size of files
- date and time of the files
is opposite as is I see it in other place, specifically I checked in:
- windows file explorer
- total commander
- google disk

Just I'm not sure if this is on purpose or by mistake.

Bye and thank's for your free work!

**Comment by alcalbg** [comment]
Yes, it's a bug, nice catch. Thanks!
