### ISSUE TITLE
How to add Footer Details & Change Logo & Default Colours

### ISSUE THREAD

**Issue by b4allb4u** [filegator/filegator#85]
Hi @alcalbg , is there any possibility to add footer details and change logos.If yes, Pls guide us how to add footer detail along with logos. 

Thanks in Adv.

B4ALLB4U.

**Comment by alcalbg** [comment]
Yes, you can do this in configuration.php file, look for `logo` and `add_to_body` variables. You can also make use of `add_to_head` to add some css like so:

```
'add_to_head' => '<style>
    html{height:inherit!important}
    .footer{background-color:white!important}
  </style>',
'add_to_body' => '<div class="footer has-text-centered"><b>My footer</b></div>',
```

**Comment by b4allb4u** [comment]
Hi @alcalbg Excellent. thanks a lot for your inputs.
![image](https://user-images.githubusercontent.com/24243794/81972059-ac893280-963f-11ea-9240-42e5bbcc788d.png)

**Comment by b4allb4u** [comment]
Hi @alcalbg .  I have made some changes to the default color.  could you pls help me on how to rebuild npm. there is any documentation on how to rebuilt the npm ?. 

Thanks in ADV.

**Comment by alcalbg** [comment]
Have you tried this: https://docs.filegator.io/development.html

Documentation can be improved, can you tell me which parts are fuzzy?

**Comment by kocane** [comment]
@alcalbg Is it possible to change the default green style to something else without npm, i.e. just modifying configuration.php?

**Comment by alcalbg** [comment]
> @alcalbg Is it possible to change the default green style to something else without npm, i.e. just modifying configuration.php?

Only by adding <style> with add_to_head like [here](https://github.com/filegator/filegator/issues/85#issuecomment-627898044)
