### ISSUE TITLE
need manual refresh page when move/copy files

### ISSUE THREAD

**Issue by vagra** [filegator/filegator#86]
**Describe the bug**
when move files to other location, the filelist does not auto refresh.

**To Reproduce**
1. go to some folder;
2. Select some files, then click 'Move' or 'Copy' button;
3. in the popup window, click a destination folder;
4. then popup window closed, but the filelist does not auto refresh, must manual refresh the page to view the changes.

**Expected behavior**
when popup window closed, the filelist auto refresh.

**Environment (please complete the following information):**
 - FileGator Version: 7.4.0
 - Server: Nginx, Win10/CentOS7.8

 - PHP Version: 7.3.11/7.2.27
 - Browser: chorme, firefox, edge

**Comment by alcalbg** [comment]
Thanks, I saw this too. Sometimes it works but sometimes you have to refresh manually. I guess some async/await is missing...

**Comment by vagra** [comment]
I add `this.loadFiles()` to `copy()` & `move()` method in frontend/views/Browser.vue, resolved this problem:

```
    copy(event, item) {
      this.$modal.open({
        parent: this,
        hasModalCard: true,
        component: Tree,
        events: {
          selected: dir => {
            this.isLoading = true
            api.copyItems({
              destination: dir.path,
              items: item ? [item] : this.getSelected(),
            })
              .then(() => {
                this.isLoading = false
                this.loadFiles()                // Add this line resolved this problem.
              })
              .catch(error => {
                this.isLoading = false
                this.handleError(error)
              })
            this.checked = []
          }
        },
      })
    },
```

**Comment by alcalbg** [comment]
Thanks, your fix worked
