### ISSUE TITLE
Where to put the multilanguage file to make Filegator support other language interface?

### ISSUE THREAD

**Issue by baoang** [filegator/filegator#9]
Hi, I see in [FAQ](https://www.file-gator.com/faq) that Filegator support many other languages in addition to English and German, but after I obtained the [language pack](https://file-gator.com/gator/languages.zip) from [File-gator.com](https://file-gator.com), I cannot see where to put those language files.

I downloaded the pre-built package. Is that I need to make some new adjustment, say create under the main dir the languages dir?

**Comment by alcalbg** [comment]
Hi,

You are looking at the old documentation. Please refer to new docs located at https://docs.filegator.io

For translations see this section: https://docs.filegator.io/translations/default.html

The new version does not support all the languages yet but we're catching up quickly.
