### ISSUE TITLE
Support for mp4 preview

### ISSUE THREAD

**Issue by MrStefanW** [filegator/filegator#94]
As of now you have to download the video in order to view it. Will you be able to implement a video preview?

**Comment by dutchtom91** [comment]
I would also love this or a way to turn off the encrypted url.

**Comment by eszel** [comment]
Hi there! I thought I solved our problem, but need to restart the search, because of this issue... :( We need video streaming also! :)

**Comment by alcalbg** [comment]
See if #141 helps
